### ISSUE TITLE
roundcube html body shows as plain text when att added

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1045]
customer contact (for me to inform then when it's fixed) https://mail.google.com/mail/u/0/#inbox/16249081a3b363ec

**Comment by tomholub** [comment]
contributor: basically install RoundCube, assuming it's free and accessible, and send a few encrypted emails from RoundCube to FC

typically we test:
1) just text, encrypted
2) just text, signed
3) just text, encrypted + signed (current bug in FlowCrypt will not show sig)
4) html text, encrypted
5) ... ...
9) small encrypted text, pdf and image attachments

**Comment by tomholub** [comment]
* send these emails to flowcrypt.compatibility@gmail.com where you will be given access

**Comment by tomholub** [comment]
The issue reported by customer what that an attachment showed two times, and not able to decrypt it in FlowCrypt:
![image](https://user-images.githubusercontent.com/6306961/55107853-3556af00-50ca-11e9-905e-f690faadb514.png)

**Comment by tomholub** [comment]
> Good day,
> 
> I'm now not able to download a decrypted GPG file from an email attachment, using gmail in chrome. Some weeks ago, this was possible. The sender used my public key.
> 
> I'm getting this message:
> File is ready.
> Right-click the link and select Save Link As
> DECRYPTED FILE
> 
> When I download this file, it still is the encrypted GPG file.
> 
> What am I doing wrong?
> 
> Thanks.

**Comment by tomholub** [comment]
If you do find an issue, please document it here. Afterwards please attempt to fix the issue in FlowCrypt, or if not enough time is left, describe what have you tried or where you got stuck.

**Comment by tomholub** [comment]
(reserving issue as a task for upcoming interviews)

**Comment by tomholub** [comment]
Once tested, you can also add Roundcube to docs: https://flowcrypt.com/docs/technical/openpgp-compatibility.html

**Comment by tomholub** [comment]
@michael-volynets this seems to be the only issue currently assigned to you. I will assign you more, but please start with this one so that it doesn't end up being pushed back. Thanks!

**Comment by michael-volynets** [comment]
@tomholub sorry for the delay, I've just seen your last comment. 
I was trying to install RoundCube before but I got some problems while installing it so I put it off. 
I'm going to try to install it again now.

**Comment by michael-volynets** [comment]
It took me a lot of time (with all my tries to install it about 3 - 3.5 days) to install Roundcube because I'm not familiar with PHP and Apache2.

But finally, I installed Roundcube and here are the results of tests.

1) Text, Encrypted - Flowcrypt successfully decrypted the message 
2) Text, Signed - Works. I can see the email label.
3) Text, Encrypted + Signed - Doesn't work. I can't see the email label but the message was decrypted. I will check it after this testing. (message link (compatibility account): https://mail.google.com/mail/u/5/#inbox/WhctKJVRNJThBCwlprdcHTMntvBJkHmxprxQJlbghVvGlkSfjhLLXWPPDQKWhVcflgBMDSV)
4) HTML + Encrypted - Works without issues.
5) HTML + Encrypted + Signed - Unfortunately, it has the same behavior as the third one but all the HTML tags were displayed correctly.
 6) HTML + Attachment + Encrypted - Doesn't work. The attachment is added but the message shows up the plain text. (https://mail.google.com/mail/u/5/#inbox/WhctKJVRNJThBLJsBKHJHmtNnZmBmKWlDBdfxhRdVlXSRpjBTkLHPmVMNFqxbZkjMrJGBpB)
7) Text + Attachment + Encrypted - Works good.

Yes, there are some issues we need to check.
Should I create a new issue in Github or we leave this open until it's fixed

**Comment by tomholub** [comment]
I know about the issues when signatures don't show on encrypted messages.
I'm planning to fix it (affects all such messages).

**Comment by tomholub** [comment]
I cannot find the issue, so I'll make one.

**Comment by tomholub** [comment]
Issue 3) and 5) now covered here: #1772

**Comment by tomholub** [comment]
Actually, overall it's looking good. The only outstanding issue other than #1772 is that it shows plain text instead of html version of the text, which is actually not too bad.

https://mail.google.com/mail/u/flowcrypt.compatibility@gmial.com/#inbox/WhctKJVRNJThBLJsBKHJHmtNnZmBmKWlDBdfxhRdVlXSRpjBTkLHPmVMNFqxbZkjMrJGBpB

Thank you for investigating this! I'll rename this issue appropriately and mark it for resolution sometime later.

**Comment by tomholub** [comment]
It is actionable, but don't want to do this anytime soon

**Comment by tomholub** [comment]
closing as low impact
