### ISSUE TITLE
Interact with GPG on my local machine

### ISSUE THREAD

**Issue by Queuecumber** [FlowCrypt/flowcrypt-browser#1068]
No offense but I would rather not give my private key to anyone. It would be nice if there was an option to ask GPG on my local machine to do the signing and encryption/decryption. Similar to how mailpile does it.

**Comment by tomholub** [comment]
Thanks for the request. For clarification, when you import the key into FlowCrypt, it will be kept in local extension storage.

I will close this for now - not because it is a bad idea (I think it's a good idea), but because GPG introduces a level of complexity on both the user side as well as the technology side that I do not want to see in FlowCrypt.

We are planning to work with hardware tokens / yubikeys - see https://github.com/FlowCrypt/flowcrypt-browser/issues/964
