### ISSUE TITLE
Recipient is there in the email draft, but FlowCrypt thinks it's not

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1072]
This is hard to reproduce, but occasionally, when I write a new email, and I've added a new recipient, write portions of the email, then save it as draft, some time later (after closing and restarting the browser, or changing to a tab, then coming back to Gmail), and reopening the draft to work on it.

When trying to send the email, FlowCrypt will complain that there's no recipient, but the recipient is there in the draft!

**Comment by tomholub** [comment]
I'm adding actionable tag in the sense that we should triage it.

Possible sources of trouble: 
 - maybe there is a race condition filling up recipients when loading from draft and evaluating recipients
 - maybe we fixed it since. The report is from about time before we aggressively started to use async / await and sometimes weird race conditions would happen.

contributor: try this a few times, if you cannot reproduce it, please close.
