### ISSUE TITLE
db_denied err user clarification

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1124]
In Firefox 60.0.2 64-bit on Windows, clicking on the FlowCrypt button shows:

FlowCrypt cannot function because browser IndexedDB is disabled
If you are on Firefox, check that indexedDB.enabled is set to true in browser settings.

indexedDB.enabled is set to true.

**Comment by tomholub** [comment]
Can you please create another default Firefox profile, and try it there? If it works, please examine the differences in settings - it would be very valuable to find out what is causing it, so that we can advise other users.

Also try temporarily disabling other extensions.

**Comment by kofiav** [comment]
I'm having the same issue on Firefox 62.0 64-bit on Ubuntu. IndexedDB.enabled is set to true, but I am still getting this message:

![flowcrypt](https://user-images.githubusercontent.com/4621203/46089522-b4e7dd80-c17c-11e8-9b05-a1fef651d169.png)

**Comment by tomholub** [comment]
@kofiav Can you please start FF with `firefox -P`, create a new profile and try to install on that profile? Please let me know if that one work, so we can find the culprit.

**Comment by kofiav** [comment]
I found out what is causing the issue. To recreate this "bug":
- Create a new Firefox profile
- Install FlowCrypt
- Go to Preferences - Privacy & Security - History
- Set it to "Never Remember History" or "Use custom settings for history" with "Always use private browsing mode" checked. 

Looks like changing the history settings to be more restrictive prevents FlowCrypt from accessing IndexedDB. I would suggest adding a more informative error message here (https://github.com/FlowCrypt/flowcrypt-browser/blob/6a96115dc06395deac16adf9f87c2dddedf20162/chrome/chrome/settings/fatal.ts#L24-L26) so that any other users who encounter this issue can troubleshoot more easily.

**Comment by tomholub** [comment]
Todo: Please try the above on Firefox and make sure the error message shows something helpful to the user in terms of how to avoid it, based on Victor's info above.

**Comment by michael-volynets** [comment]
I have checked that and FlowCrypt shows me this page:
![image](https://user-images.githubusercontent.com/49104848/56214141-fdf27700-6065-11e9-86e7-2236a7c32ac9.png)

I've checked this on the production version of FlowCrypt (I downloaded it from https://flowcrypt.com/download)

**Comment by tomholub** [comment]
That's good, but it doesn't tell the user all of the ways how to break the settings to cause this page to show (or all of the settings they should make sure to check).

It only mentions indexedDb. But their problem may be `Remember History`, so please add a note to guide users to check that setting too.
