### ISSUE TITLE
test encrypting and decrypting naughty strings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1368]
https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by tomholub** [comment]
The result of the testing should be new issues created on GitHub for any strings that cause trouble. Please reference the issues here if any, or note that no issues were found.

**Comment by schmorrison** [comment]
Ok so I made a branch (issue-1368-test-naughty-string) which likely should not be merged because in its current state the amount of work blocks the UI for about 90 seconds.

It fetches the list of naughty strings from the github repo and tests each one doing an encrypt/decrypt then compares the decrypted data with the original string. I only see a single failed decryption currently:

```&#65279;```

Which is the 'Zero Width No-Break Space' unicode character. If required I can make an additional issue for this particular string.

**Comment by tomholub** [comment]
Thanks! If that's the only failure, that would be a great result. You can ignore that and close this issue. Good work
