### ISSUE TITLE
clarify manual backup security

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1571]
related #1319

**Comment by Redsandro** [comment]
https://github.com/FlowCrypt/flowcrypt-browser/pull/1319/commits/a132f88125fe6cbc2366c9f19b0d1efe1f17a711

**Comment by tomholub** [comment]
Yup, it should more or less state the opposite, we'll clarify it with upcoming release.

**Comment by tomholub** [comment]
@Redsandro Does this look better?

![image](https://user-images.githubusercontent.com/6306961/53298932-3e830080-382c-11e9-9577-63111a08f5a1.png)

**Comment by Redsandro** [comment]
I guess it's better, but it's still chaotic.

1. First item is good!
2. Second item is too long. Remove the second sentence ("You will also need...") because it is implied by both logic and the third sentence.
2b. If you don't want to remove the second sentence, it needs to be moved to the first item, because the exact same thing applies there, but we haven't read it yet.
3. Labels are chaotic. I prefer to change them altogether, but perhaps at least they can be drawn in some kind of aligned position to be less chaotic.

**Comment by tomholub** [comment]
How about this? I agree it would use an overall redesign, to put it a bit more in order, but I'd leave that for another day. Hopefully this is an improvement.

![image](https://user-images.githubusercontent.com/6306961/53300222-33d06780-383c-11e9-9e82-dc8bb38453b7.png)

**Comment by tomholub** [comment]
I'll close this as I need to do a release, but definitely still want to hear your feedback, we can always improve it in a followup issue.
