### ISSUE TITLE
clciking to view/hide pass phrase should update affect all pass phrases in frame

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1586]
So that this doesn't happen

![image](https://user-images.githubusercontent.com/6306961/53914859-7f61ed00-4056-11e9-8bc3-5ddfa7e004af.png)

**Comment by tomholub** [comment]
This is interesting - you'll find this form on the setup screen (generate a new key).

I can click the "eye" icon individually, to hide or show the pass phrase. But it would make more sense that clicking the eye would affect all pass phrase inputs on the page automatically, not just the one I clicked.

You could try this on a testing gmail account.

If you need to re-test on the same account:
1) FlowrCrypt Settings -> Additional Settings -> Experimental -> reset account
2) give it a wrong pass phrase during setup
3) click the setup again link on the bottom

**Comment by limonte** [comment]
@tomholub 

> click the setup again link on the bottom

Could you please be more specific here, which link exactly should I click in order to get to the form from the issue description? There's the "Skip recovery and set up encryption again. Your previous encrypted emails will be unreadable." link, but that'd make my previuos encrypted emails unreadable which is not what I want.

**Comment by tomholub** [comment]
I've sent you credentials for a test email (over email).

**Comment by limonte** [comment]
Thank you!
