### ISSUE TITLE
allow builds on windows

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1618]
Most of the incompatibility is probably using unix commands. I would use https://www.npmjs.com/package/shelljs for that.

In particular, I don't want to make our `gulp.js` (much) more complicated. In fact, I would hope to deprecate gulp one day, it has been a pain.

**Comment by michael-volynets** [comment]
Seems like it doesn't add types files when it runs  "runTscContentScripts" and "runTscExtension" tasks.
The errors I get are related to "dompurify":
`Error: Command failed: node ../build/tooling/tsc-compiler --project tsconfig.content_scripts.json
C:/Projects/flowcrypt-browser/extension/js/common/browser.ts (650,7): Argument of type '{ SAFE_FOR_JQUERY: true; ADD_ATTR: string[]; ALLOWED_URI_REGEXP: RegExp; }' is not assignable to parameter of type 'Config'.`

Do you know why that's happened? I think the issue is somewhere in tsc-compiler.ts because I don't get those errors in my IDE (VScode) when it checks all the typescript files.

If I change 'path' to incorrect one in tsconfig.json I see those errors in my IDE

**Comment by tomholub** [comment]
I don't know. Maybe the paths work differently on windows, and one needs to work with `\` instead of `/` or whatever. I haven't used windows for over a decade, and have near zero knowledge of developing on that platform.

Like this piece of code:
```js
tsconfigAbsPath = path.resolve(tsconfigAbsPath || './tsconfig.json');
const tsconfigAbsDir = tsconfigAbsPath.replace(/\/[^/]+$/g, '');
```
Could maybe work differently on windows.

**Comment by tomholub** [comment]
If you got stuck on this, you can maybe share some pieces of code in the comment and then un-assign the issue.

Maybe one day me or you or someone could come back to it.
