### ISSUE TITLE
Encrypted Contact Page doesn't show current account

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1742]
I have 5 Flowcrypt accounts but they all show me the same Encrypted Contact Page.
ScreenShot:
![image](https://user-images.githubusercontent.com/49104848/59039968-74e60800-887e-11e9-833f-051460d49f55.png)

On Screenshot, you can see that currently, I'm using "michael.flowcrypt@gmail.com" (in the top-right corner) but I see  Encrypted Contact Page for "michael.volynets@startupsoft.us"

**Comment by tomholub** [comment]
Yes, this and many other similar issues are due to the way accounts are handled. Currently, it will only use one of the installed accounts for encrypted contact page, trial activation, paid subscription, etc.

I plan to fix this (it involves backend work as well) but don't see an issue for it, so I'll make one.

**Comment by tomholub** [comment]
Thanks for noting it!

**Comment by tomholub** [comment]
This will be fixed by #1743
