### ISSUE TITLE
Fix Script 'test_chrome_consumer' on Windows 

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1802]
The Script doesn't work on Windows Devices, 
it throws this error:
![image](https://user-images.githubusercontent.com/49104848/60723917-aadde100-9f3d-11e9-81ef-374a5eeca4ee.png)

I guess something wrong with the path but need to investigate it more

**Comment by tomholub** [comment]
Yes, the mocks cannot be built on windows yet, they use `cp -r xxx yyy` shell command in the build process.

As soon as I'm done merging #1799 , build won't work on windows whatsover.

I recommend, on Windows, instead of trying to keep the build process multi-platform, to find a way how to run shell scripts from windows.

https://stackoverflow.com/questions/6413377/is-there-a-way-to-run-bash-scripts-on-windows

Then run the build process from there.

**Comment by tomholub** [comment]
Last resort could be a docker container for building, but I would really want to avoid bringing in docker.

**Comment by tomholub** [comment]
For now I'm closing this
