### ISSUE TITLE
Inconsistent logo on the after-install page

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1898]
Small detail, but the logo is grey on the after-install page and green in the extensions toolbar. I believe the logo should have the same color everywhere.

![image](https://user-images.githubusercontent.com/6059356/62848562-e01be280-bce4-11e9-9b16-5576fd1d423d.png)

**Comment by tomholub** [comment]
I made it gray because I was standing behind a test user and they actually clicked on the icon on the left! Several times? Then they paused, looked around, and followed the arrow ¯\\\_(ツ)\_/¯

Maybe we make it green again, but with 50% opacity? Or whatever opacity you find appropriate. To make it less compelling to click.

**Comment by tomholub** [comment]
(why - I want to teach them to use the one in the corner)
