### ISSUE TITLE
Consider a link/button in Gmail front-page UI leading to the "FlowCrypt Settings"

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1912]
There is a link to the FlowCrypt Settings:

![image](https://user-images.githubusercontent.com/6059356/62865196-7a484e80-bd16-11e9-9212-a260e284a3ac.png)

And it does make sense for it to be there, but personally, I didn't find it right away and was looking for something like "the green cog icon" besides the default grey cog icon here:

![image](https://user-images.githubusercontent.com/6059356/62865258-a9f75680-bd16-11e9-8508-ddd888bcc5d5.png)

There might be some reasons not to have it there, but I don't see those atm, feel free to close this issue as invalid is you think that the current link is on its irght place.

**Comment by tomholub** [comment]
We were trying to be a bit less invasive. The standard way to access settings should be through the browser action button (like during setup). But not all users get it. Some go fishing for it in Gmail settings, and for those, we added the tab-link.

Every time (many times) I add a new element directly to Gmail, I'll get users tell me off for "intruding their work space". So I'm trying to keep the Gmail additions to a minimum.

You'd be surprised (or maybe not) at the subtle ways things can break for users. For example, even the most basic addition - the secure compose button - will take up a bit of space vertically. That means the user can see a little fewer email folders on the left in the gmail menu that still fit on the screen, above the hangouts section. We literally had user uninstall the extension because they can "no longer access trash" or something like that. Of course, for the minority that write me, I can explain to them that they can drag down the hangouts section or just scroll the email folders. But it does give me a pause every time I'm about to add another UI element directly to gmail.

I guess this conservative approach is what led us to hide it in the settings, combined with the fact that the standard way is to actually use the extension icon in the browser.

So maybe we'll not take action on this one, but it's a fair & valid observation, with unclear right answer.

**Comment by limonte** [comment]
I have to agree with what you're saying about "intruding people's work space". I'm one of those who can be annoyed by the smallest changes in UI :laughing: 

And actually, I agree with being as less intrusive to the original UI as possible. So I'll close this issue.
