### ISSUE TITLE
evaluate removing tabindex="-1" on #input_from

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1925]
From http://webaim.org/techniques/keyboard/tabindex

> A tabindex="-1" value removes the element from the default navigation flow (i.e., a user cannot tab to it), but it allows it to receive programmatic focus, meaning focus can be set to it from a link or with scripting.** This can be very useful for elements that should not be tabbed to, but that may need to have focus set to them.

As a user, I'd like to be able to access `#input_from` from a keyboard. Is there any particular reason to exclude it from the taborder?

**Comment by tomholub** [comment]
I think it may have helped me attack a particular bug. So maybe I went ahead and sacrificed the tabbers. You can try to remove it and then see if it still behaves properly when you remove focus with a mouse, after a valid email entry and also after invalid entry. 

Further, hitting tab while entering recipient means "done entering this one, move onto next recipient". Same with comma, and maybe enter. If all of this works after removing it, by all means do. Thanks for a asking.

**Comment by tomholub** [comment]
I think I know what the reason was. When there is just one email in input_from, the from-select-option was hidden but I think it would still trap focus when tabbing. So you would need to double-tab to get from recipients to body. It wasn't smooth. Please test if it's still the case, and if it is, see what could be done about it.
