### ISSUE TITLE
comma in name causes problems

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2166]
Reproduce:
1) set `Name, XYZ` as a name on Gmail account
2) send a message to anywhere
3) the mime will show `From: XYZ <email@email.com>` but it should show `From: "Name, XYZ <email@email.com>"` (not sure if I escaped that properly)

Anyway the point is that it seems that we are passing just `XYZ` as a name to mime encoder, where it should be `Name, XYZ` - wrongly cropped around the comma.

**Comment by michael-volynets** [comment]
The issue is in `emailsjs-mime-builder.js`, I will try to update it, maybe it will help

**Comment by michael-volynets** [comment]
Actually in `emailjs-addressparser`

**Comment by michael-volynets** [comment]
I found another interesting bug while investigating this one.

When you change your Google Name like `<email>, <your name>` (e.g. 'some.email@gmail.com, My Name') then all emails that you sent will be sent to the `<email>` (in the example, to 'some.email@gmail.com') and to the original recipient.  :laughing:

I couldn't update the library but we don't need to update it either way because they haven't fixed the issue,
can I update `emailjs-addressparser.js` file to fix the issue?

**Comment by tomholub** [comment]
I was talking to the emailjs repo owner earlier. They don't have time to maintain it. We may end up maintaining emailjs going forward.

But changes like this are not simple - it's not just about making it behave right for our purposes. It has to strictly follow the spec. There have to be tests for that, etc. https://tools.ietf.org/html/rfc2822

Sure, we could just fix it in the library that we use, but maintaining it that way is not sustainable. On the other hand, we don't really have time right now to get into maintaining emailjs, learn about the test suite, etc.

What I'd suggest, for now, is to leave the library as is, and strip all `<>,` characters from the Google name. That should fix the issue at hand, and then we can make plans to possibly properly maintain `emailjs` in the future.
