### ISSUE TITLE
help @limonte login into shared accounts

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2224]
Tests are executing well until this screen:

![image](https://user-images.githubusercontent.com/6059356/69728783-c8e6f080-112d-11ea-8fd6-5fa959c24939.png)

Nothing is happening here and after some time this exception appears:

```
Error: waiting failed: Elements did not appear: #submit_approve_access,//div[@class='vdE7Oc' and text() = 'Confirm your recovery email'],input[type="password"],#totpPin
          at ControllablePage.ControllableBase.waitAny (/var/www/flowcrypt-browser/test/source/browser/controllable.ts:106:11)
```

**Comment by tomholub** [comment]
Yeah, that's the problem with live tests, they are finicky because of Google login. 
Check the test secrets file - you will find email, password, and a 2FA secret that you can import (eg into Google Authenticator). Try to log in on the side first, manually. If it gives you trouble, I'll help you get in.

**Comment by limonte** [comment]
Thanks, the Google Authenticator suggestion helped!

**Comment by limonte** [comment]
Actually I was wrong, the issue is still there and 2FA doesn't help because Google doesn't accept it as an option:

![Peek 2019-12-02 15-46](https://user-images.githubusercontent.com/6059356/69964441-1b078780-151b-11ea-9255-5b1765bc0fe3.gif)

**Comment by tomholub** [comment]
@limonte I recommend we connect over chat and get this resolved together, by me giving you whatever access code it asks.

I can be found on Keybase as `@tomjh` (keybase needs to be installed as a chat app on your desktop, not the browser extension). Otherwise I'll invite you to slack if you prefer (for folks who don't want to install stuff).

**Comment by tomholub** [comment]
Were you able to log into flowcrypt.compatibility after all?
