### ISSUE TITLE
test drafts with a <tag>

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2292]
followup from #2284

**Comment by tomholub** [comment]
There used to be a bug until recently:

1) save a draft that contains `hello<draft>here`
2) open the draft
3) it would only say `hellohere` which is wrong. The html content was getting sanitized away, but it was supposed to be escaped.

Now it correctly shows `hello<draft>here` when you open the draft

Please make a test for this. Thanks!

**Comment by tomholub** [comment]
issue was fixed here among other things https://github.com/FlowCrypt/flowcrypt-browser/pull/2285

**Comment by michael-volynets** [comment]
I have got two ways to create a test:
1) Store new draft message in the mock data and then test the message (Easier one)
2) Create a draft directly in the test and then test this newly created draft. (harder one because we don't have methods to create save drafts in our API mock)

I'm asking about it because I don't know where the bug had happened. Had it happened while saving a draft or while loading?
If it had happened while saving a draft then I have to make a test using 2nd way but if while loading then 1 way of testing should suit us.

**Comment by tomholub** [comment]
It happened while rendering (loading). You can use the simpler method. Thanks for asking!

**Comment by michael-volynets** [comment]
Okay, thanks!
