### ISSUE TITLE
Increase min-height of pgp_block.

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2434]
When a modal dialog is shown inside Pgp_block that has a small height (it may contain a little of text or just a PGP/Mime attachment) the modal dialog (look at the screenshot) doesn't fit inside the block.
I would recommend increasing pgp_block height or show this modal dialog outside the block (show it on the whole page).

Attachment:
![image](https://user-images.githubusercontent.com/49104848/71366867-ed5aaf00-25ab-11ea-848a-9d63fdaea2bf.png)

**Comment by tomholub** [comment]
Because I would prefer to not increase the block height even further (affecting email usability - I think), and would also prefer not to complicate things with passing around messages and showing them on the main frame, I suggest a css media rule that is active below certain height, that would render the dialog differently.

**Comment by limonte** [comment]
My mistake, reopening.
