### ISSUE TITLE
Getting the "Not logged in" error when trying to renew a subscription

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2461]
![1](https://user-images.githubusercontent.com/6059356/71730707-88287880-2e4b-11ea-84c0-a511cacd4af0.gif)

Happening in both browsers.

Expected: the ability to proceed with payment because I'm logged in.

Probably, the issue will be resolved by logging in with the Gmail popup, but I didn't log in additionally because if this is an actual issue, I'll be able to reproduce it and debug.

**Comment by limonte** [comment]
False alarm, sorry. I was logged out.

**Comment by tomholub** [comment]
Somewhat confusing, I know. Logging into Gmail (getting google credentials) does not automatically log you in or create a flowcrypt account (an account with out own backend).

That's because most users don't need a FlowCrypt account. Only when it's needed will it ask to authenticate with FlowCrypt as well. Then it will save uuid, and re-use it next time to communicate with backend.
