### ISSUE TITLE
attachments with s/mime produce garbled messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2734]
When opening an s/mime message on a client without s/mime (tried Gmail), it just shows the bytes.

I would have expected it to show as an attachment (I vaguely recall trying to open such message before). Can you have a look?

![image](https://user-images.githubusercontent.com/6306961/79441208-7d42bf80-7fc6-11ea-97c4-533873e5f987.png)

Also, have you tried to open such message in an s/mime client, after integrating it?

We're getting there.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2712#issuecomment-614537259_

**Comment by wiktor-k** [comment]
Hmm... upon initial investigation I see this just fine on the receiving end: (my gmail with no flowcrypt extension):

![2020-04-17T11:28:52,845386714+02:00](https://user-images.githubusercontent.com/1718963/79554657-a898dd80-809e-11ea-87fb-ae5efbf84625.png)

And it looks OK on the sending end (with flowcrypt):

![2020-04-17T11:35:25,863799819+02:00](https://user-images.githubusercontent.com/1718963/79555242-8ce20700-809f-11ea-8ac0-c37db37be202.png)

S/MIME examples in the RFC also mention one inline message instead of encrypted attachment: https://tools.ietf.org/html/rfc4134#section-5.3

I'll need to investigate this further. Could you send me the raw message that you saw (via e-mail or so...).

**Comment by tomholub** [comment]
Cannot reproduce when emailing myself

![image](https://user-images.githubusercontent.com/6306961/79565909-265de880-80a1-11ea-87a0-cf6481a06ce2.png)

I'll email you the problematic message. You can drag it into Thunderbird from your desktop, which will save it on imap, which will allow you access the message from Gmail interface (even if this is not really a message for your account).

**Comment by wiktor-k** [comment]
> You can drag it into Thunderbird from your desktop, which will save it on imap, which will allow you access the message from Gmail interface (even if this is not really a message for your account).

:+1: Did the same trick when working on K9 :)

**Comment by tomholub** [comment]
I could not reproduce it.

The one that messed up included an attached public key, but even if I choose to attach a public key now, it won't attach it anyway (with s/mime message). Which it should. So I'm having a hard time trying to reproduce it.

![image](https://user-images.githubusercontent.com/6306961/79568126-d5e88a00-80a4-11ea-9e04-15b7f7d46bab.png)

**Comment by wiktor-k** [comment]
I don't think attachments work with S/MIME, maybe they produced garbled messages. This is a good ticket to keep. I'll investigate it further after I'm done with other "actionable" tickets.

**Comment by tomholub** [comment]
closing in favor of #2734
