### ISSUE TITLE
Error encrypting message: Missing private key parameters

### ISSUE THREAD

**Issue by drzraf** [FlowCrypt/flowcrypt-browser#2743]
I imported my key. Passphrase is ok.
But it fails at the first attempt to send a signed email with `Error encrypting message: Missing private key parameters`.

**Comment by tomholub** [comment]
Hello,

how was the key created, in which software?

Please run the key through FlowCrypt Settings -> Additional Settings -> Experimental -> OpenPGP Compatibility Test, and share the output.

**Comment by drzraf** [comment]
```
(12) PK 0 > Encrypt/Decrypt test: Encryption with key was successful  
(13) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Cannot check encryption status of secret keys in a Public Key  
```

To export my key from Gnupg keyring I...
1. Updated my key to use an empty passphrase (because I didn't want to share the passphrase with the browser environment)
2. Exported using `--armor --export-secret-subkeys`

**Comment by tomholub** [comment]
Sorry for the lack of activity on this issue. I'll close it until we can have a similar private key to test with. Without it, it's very hard to attempt a fix.

**Comment by drzraf** [comment]
Is it at least possible to get some insight/documentation about how to export a password-less key from GPG and import it within flowcrypt?

**Comment by tomholub** [comment]
I'm not sure - you should not need to export it in plain, it's ok to export it pass phrase protected, and then enter that pass phrase into FlowCrypt. 

Looking at this again, there are a few interesting parts in your dumps:

```
(15) PK 0 > Encrypt/Decrypt test: Encryption with key was successful  
(16) PK 0 > Encrypt/Decrypt test: Decryption with key succeeded  
(17) PK 0 > Sign/Verify test: [-] Exception: Error: Missing private key parameters  
```

It was using the subkey for encryption and decryption, but it seems like it wanted to use the primary key for signing. But the primary key is not present because you used `--export-secret-subkeys`.

This is because your subkey is missing signing key flag:
```
(22) PK 0 > SK 0 > SIG 0 > Key flags: [-] 12  
```
If I'm reading this correctly, you have 0x04 and 0x08 flags (both for encryption) but not 0x02 (signing). This is standard, typically signing is done by the primary key.

So you have a choice of either exporting the full key:
```
gpg --output private-key.asc --armor --export-secret-key your@email.com
```

Or modifying your key to include the signing flag on the subkey, too, then exporting the same way as before.

**Comment by drzraf** [comment]
Insightful. I'll let you know how it goes.
