### ISSUE TITLE
draft buttons should include identifier + enforce

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#279]
part of #143

plus do not enforce the identifier on read for drafts created before this was deployed

**Comment by tomholub** [comment]
@seisvelas I worry this may be a security issue. We leave a an identifier like `[draft:some-id]` in saved drafts, which gets picked up by the content script next time we encounter an encrypted draft (particularly new message draft - unrelated to any conversation).

I wonder what would happen if someone sent me a `[draft:nonsense]` and I opened it?

Could you have a look at this and try to exploit it?

**Comment by seisvelas** [comment]
>I wonder what would happen if someone sent me a [draft:nonsense] and I opened it?

Nothing, it doesn't open it as a draft or anything, just opens normal. I've tried lots of ways to trick FlowCrypt into opening received mail as a draft but it won't do it. I think because it only detects drafts via compose.ts, which isn't in charge when you're just reading an email (even if encrypted). And when you open a response, it's only checking your response input area for signs of being a draft, so still no risk.

I'll keep trying!

**Comment by tomholub** [comment]
That means this task may not be actionable, which is good news - it's the
oldest task we have. We can close it then. Thanks!
