### ISSUE TITLE
Attachment preview is not working in rendered replies

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2831]
### Steps to reproduce

1. Go to any encrypted thread
2. Disable rich-text (if enabled)
3. Add an attachment
4. Write anything and reply
5. Wait until the reply is rendered
6. Click on the attachment to preview it

![image](https://user-images.githubusercontent.com/6059356/86800131-5f43a300-c07b-11ea-84bf-bcba2074b302.png)

### Expected behavior

Attachment preview is shown

### Actual behavior

Nothing happens

Downloading attachments still works as expected.

**Comment by tomholub** [comment]
This would be a good thing to add tests for, too - easy to overlook when this breaks

**Comment by limonte** [comment]
Agree, will add a test. @tomholub wdyt should I fix this issue before writing the blog post about the attachment preview feature?

**Comment by tomholub** [comment]
Fair, that would make sense!

**Comment by limonte** [comment]
@tomholub I'd need you help on the direction.

Here's the cause:

![image](https://user-images.githubusercontent.com/6059356/86804930-0f1b0f80-c080-11ea-9713-a3277d981a4f.png)

`attachment.htm` frames are rendered **inside** an iframe with reply, so `parentTabId` for attachments is not the root `tabId`, but the `tabId` of the reply iframe.

What do you think should attachments be moved outside reply iframe or in `attachment.ts` I should somehow detect the root `tabId` (here: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/attachment.ts#L231-L233)

**Comment by limonte** [comment]
@tomholub ping

**Comment by tomholub** [comment]
The easiest fix would be to have a way to give a `parentTabId=parentTabId` instead of `parentTabId=myOwnTabId` when the frame is creating these attachment frames. Then the attachment frame will be calling the super-parent automatically. BUT I don't know if this will work smoothly otherwise. If it does, you can go with it.

If it doesn't, or requires a lot of witchcraft, it may be a more proper solution to take the attachments out of the frame and render them like regular attachments, but here the problem is, how to pass data to them safely? I don't know what we do today. If we pass the data as url parameter, then thainsidet is safe in the context of placing the attachment frame inside our own iframe, but not when placing the attachment frame into Gmail webmail directly (the Gmail page could just read the data from the iframe url, which is part of its own dom tree).
