### ISSUE TITLE
Attachments for signed-only messages are rendered as encrypted

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2834]
While working on #2832 I noticed that attachments for signed-only messages are rendered as encrypted. That's wrong because attachments are not encrypted for signed-only messages.

Because of that, the attachment preview feature is not working correctly because it's trying to decrypt attachments:

![3](https://user-images.githubusercontent.com/6059356/87234685-24739f00-c3dc-11ea-9aa0-47bc64bd0933.gif)

**Comment by tomholub** [comment]
Now I see this properly - this happens when the sent message is rendered immediately following sending it. That is why the signed message is rendered with our own UI (normally, it would be rendered with Gmail UI if you exit the conversation and come back - exactly because it's not encrypted.

I think that's a fair usecase to cover - allow user to immediately click on sent attachment to assure themselves that they sent the right thing. I do this a lot myself.
