### ISSUE TITLE
Why does Chrome extension need access to browser history?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2902]
From https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXVGskKMDbxBfgPqJjrwtxVzq

> Hello. I would really like to download the extension, but I am worried about it's permissions. Why does this extension need my browsing history? Could you quickly explain this to me or send me a link to somewhere that I could find an explanation?  Thank you.

I checked on Chrome and this appears to be true:
![perm](https://user-images.githubusercontent.com/44826516/90460456-6d98cc00-e0c9-11ea-9e5c-2aecc329a9da.png)

Is this necessary, and if so, for what?

**Comment by tomholub** [comment]
Unfortunately, chrome bundles permissions together in a way that makes it impossible to only request the permissions we use.

This particular outcome is caused by the fact that we use `chrome.tabs` to inject code into Gmail page that makes it function smootly when FlowCrypt is first installed, and during updates. But because the `tabs` permission also has other functionality on it - functionality FlowCrypt extension doesn't use or need - the user will see the "Read your browsing history" permission.

The list of requested permissions currently is:
```
  "permissions": [
    "storage",
    "tabs",
    "https://flowcrypt.com/*",
    "https://*.google.com/*",
    "https://outlook.live.com/*",
    "https://outlook.office365.com/*",
    "https://outlook.office.com/*",
    "https://graph.microsoft.com/*",
    "https://login.microsoftonline.com/*",
    "https://www.googleapis.com/*",
    "unlimitedStorage"
  ],
```

We have done some work to find a way to stop using this permission, and hope we can eventually drop it. It requires difficult changes, so for now that `tabs` permission is still needed: https://github.com/FlowCrypt/flowcrypt-browser/issues/2497
