### ISSUE TITLE
Error receiving unencrypted emails with encrypted attachments

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2947]
> Hi,
> 
> I can send and receive encrypted emails without any problems.
> However, customer send me an "normal" not encrypted email with encrypted attachment.
> I'm not able to decrypt attachment - this process leads to the following message:
> 
> "Error: Session key decryption failed..
> 
> Contact human@flowcrypt.com"

Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXpWgHFBvDczcZwfHpJlrWdGg

**Comment by tomholub** [comment]
Again, this is an issue of receiving email, which we can rectify if we have a sample of such message.

In docs, please see troubleshooting section when receiving email, and give user instructions for his sender to send us email to compatibility account.

Separately, it would be good to know which software his sender is using, because FlowCrypt does not have this functionality. There is probably a compat issue.

**Comment by tomholub** [comment]
When asking the user to arrange a compat email sent to us, the user will need to know for which public key to encrypt it for (other software will not always be able to fetch it automatically). It's good to give them a link: https://flowcrypt.com/pub/flowcrypt.compatibility@gmail.com

**Comment by tomholub** [comment]
closing for no sample, if user in fact sent a sample, please link and reopen
