### ISSUE TITLE
command to check if node_modules reflect package.json

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3005]
When we update dependency on master, I may forget to re-run npm install before release.
But I don't necessarily want to delete node_modules and reinstall before every release.
Is there a way to ask npm if my current node_module reflect what we have in package.json?

Lack of this caused #3004

**Comment by limonte** [comment]
This might be slightly offtopic, but I'd propose adding the lock file to the repo as per npm's and Yarn's recommendations:

In case of npm that'd be https://docs.npmjs.com/files/package-lock.json

>This file is intended to be committed into source repositories

But `package-lock.json` doesn't really match with the expectations of many people, here's why

- https://stackoverflow.com/q/45022048/1331425
- https://github.com/npm/npm/issues/17979

![image](https://user-images.githubusercontent.com/6059356/95753905-f3d92500-0caa-11eb-94a5-200ff8c73e8e.png)

---

That's why I'd recommend using Yarn over npm and adding `yarn.lock` to the repo. After that we could be sure that `node_modules` is the same in all environments.

**Comment by tomholub** [comment]
Something to be considered for sure, though it would be quite a change. Once we have a bit quieter period (will there ever be?) I'd like to evaluate this
