### ISSUE TITLE
flowcrypt settings -> popup -> right-click -> in new window

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3031]
I saw a customer follow this sequence - he wanted to have two settings windows open.

Maybe we should allow them to do that? (either by default, or by somehow making the right-click work).

To be precise, they right-clicked the cog icon in pupup and clicked "open image in new tab" probably thinking they are clicking "open page in new tab".

This is somewhat related to https://github.com/FlowCrypt/flowcrypt-browser/issues/2998

I'd like your input @limonte - was it a bad idea for me to always try to open settings in a single tab?

**Comment by limonte** [comment]
From POV of some users it would be unexpected that settings are forced to work in a single tab.

But from developer's POV, providing the possibility of having multiple tabs with settings means that these tabs should be synced and the syncronization will be a lot of work. If we don't syncronize tabs, all kind of unexpected things are to expect because the current UI isn't reactive and doesn't update itself when the user's data gets updated.

Example: if you open `chrome://settings/searchEngines` in two tabs and delete any search engine it'd be deleted in another one as well. 

So IMO the ability to have setting in multiple will be possible to add after converting the settings UI into the reactive one by using one of modern frameworks.

**Comment by tomholub** [comment]
Thanks for the feedback!

That would be a disaster - I don't want to make that kind of change anytime soon. I'll go ahead and close this.
