### ISSUE TITLE
ability to send s/mime attachments

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3091]
Currently we have limited s/mime support - you can enter someone's email in Secure Compose, and if that person does not have any known OpenPGP key, you can click "import openpgp key" on the bottom. While the interface all only mentions OpenPGP, it will actually let you import an s/mime key.

If you import an s/mime key, you can then send out the email and it will be s/mime encrypted.

However, attachments don't work yet. Please add attachment support, and test compatibility by reading the s/mime messages in Thunderbird.

(FlowCrypt does not yet support opening s/mime emails, so have to use Thunderbird for testing)

You can get s/mime certs for testing here https://extrassl.actalis.it/portal/uapub/freemail?lang=en

**Comment by tomholub** [comment]
This issue is for @vnikolaou

**Comment by tomholub** [comment]
Questions from @vnikolaou 

> More questions rather important.
> After debugging a little bit the code ... i understand that for attachments at least based on x509 (sending an s/mime message).. we have calls to:
> 1. <att-ui.ts>.collectEncryptAtts()
> 2. <msg-utils.ts>.encryptMessage()
> 3. <smime-keys.ts>.encryptMessage()
> Currently there is a check inside att-ui.ts that checks for pubkey.type == 'x509' and if it is true break the flow and the message is not sent from composer.

> I tried to bypass this just to see what happens.. it seems that nothing is encrypted of course normally.. and i get an exception about not found packets over encrypted.message variable

> Generally... and given that i see that we use node-forge .. what do you think it is the library(another library maybe?) or the methods from this library (node-forge) that i should focus? On the other hand in order to have it so far disabled.. does it indicate any missing functionality or limitation in this library? Do you know?

Most likely it's disabled because the s/mime functionality is basically a proof of concept. We didn't spend time on attachments yet. The lib can probably do it.

One thing to keep in mind about design: there is MsgUtil class that is general and will generally branch into pgp-specific or smime-specific functionality based on need. Then there are classes like `OpenPGPKey` which are pgp-specific, and then there should also be s/mime specific classes somewhere. What you'd want to do is look into wherever mime-encryption of messages happens (in our code that uses node-forge) and see what happens when you add attachments, and/or how to fix it.

**Comment by vnikolaou** [comment]
> Questions from @vnikolaou
> 
> > More questions rather important.
> > After debugging a little bit the code ... i understand that for attachments at least based on x509 (sending an s/mime message).. we have calls to:
> > 
> > 1. <att-ui.ts>.collectEncryptAtts()
> > 2. <msg-utils.ts>.encryptMessage()
> > 3. <smime-keys.ts>.encryptMessage()
> >    Currently there is a check inside att-ui.ts that checks for pubkey.type == 'x509' and if it is true break the flow and the message is not sent from composer.
> 
> > I tried to bypass this just to see what happens.. it seems that nothing is encrypted of course normally.. and i get an exception about not found packets over encrypted.message variable
> 
> > Generally... and given that i see that we use node-forge .. what do you think it is the library(another library maybe?) or the methods from this library (node-forge) that i should focus? On the other hand in order to have it so far disabled.. does it indicate any missing functionality or limitation in this library? Do you know?
> 
> Most likely it's disabled because the s/mime functionality is basically a proof of concept. We didn't spend time on attachments yet. The lib can probably do it.
> 
> One thing to keep in mind about design: there is MsgUtil class that is general and will generally branch into pgp-specific or smime-specific functionality based on need. Then there are classes like `OpenPGPKey` which are pgp-specific, and then there should also be s/mime specific classes somewhere. What you'd want to do is look into wherever mime-encryption of messages happens (in our code that uses node-forge) and see what happens when you add attachments, and/or how to fix it.

I agree on the facts above. Actually I have included the same conclusion in my comments below which are mainly facts about what I have found so far after debugging:

1. First, for sending s/mime messages and the certificate, what I extracted from PFX was the CERT. With this certificate sending text (only) messages, seems to be working. I tried sending the same message with the chrome extension and the thunderbird and i compared the raw messages as delivered. So the raw email is different in the body which may indicate that using the CERT in that format in the extension is not correct (even if for text seems to be working).

2. I tried sending the same text+attachments as in #1 and after commenting out the existing checks in code that preserve sending attachments with s/mime. Again the message was sent and i compared the raw messages. The content is not only different but in extension substantiallly smaller in size which surely indicate that the encrypting process was not correct with the given CERT and/or the existing forge API. However the text again was shown correctly. The attachments were ignored visually in the thunderbird UI (not shown in the email with envelope icon) when the message arrived as if they had never been sent.

3. The code indeed needs some kind of abstraction in msg-util.encryptMessage because it always return something that supposed to be OpenPGP.EncryptBinaryResult which is not the case for s/mime. Different classes and/or methods should be developed to cover the s/mime case. 


Considering the # 3, at the moment and before implementing this abstraction, I need to make sure that the code (after locally making it ignore the PGP related statements) can send properly s/mime messages (attachment and probably text). 
Given that the existing code applies a very specific approach by using the CERT (or whatever) to encrypt, then using ASN1 to DER etc.. I think that i need to read the spec (RFC) for the s/mime in order to understand much better the inner details. Definitely can be done since the thunderbird does it... so understanding the inner mechanic of s/mime encrypted message and the required steps ie. what algorithms, certificates and other concepts are involved is crucial.

**Comment by tomholub** [comment]
You should write a bit of code on the side, unrelated to the chrome extension plugin. Use the Forge library to just encrypt a bit of text as a file, and export that as a mime file. Drag the mime file over to thunderbird to import it (so you don't have to send it).

Check the code into the repository as a Draft PR so that others can help you.

**Comment by tomholub** [comment]
>  Hi Tom, I read the RFC for the s/mime v.3.1. Ok, quite interesting probably but not necessarily very useful in understanding what is exactly the problem with the current code in sending s/mime.
> I saw your message for creating some code aside... i agree but i have a couple of questions since it is something that will generate a PR.
> 1. Will it be a useful utility class or method which can be used later in code.. or you mean just for experimenting locally and sharing the code with others.. and after completing the code will be dropped?
> 2. Should it be a utility function eg. inside /extension/common for the flowcrypt-browser repository?
> 3. Same branch? another branch?
> 4. What do you mean to export (the sample encrypted text) as a mime file? I'll need to create proper headers and body etc. for s/mime .. you mean copy/paste from existing raw s/mime message and just replace the body?

I'm just recommending to find a way to debug this in a way that you reduce the amount of variables involved, and in a way where others can also be helpful.

The details depend on you. The goal is to quickly get into a situation where we can discuss code rather than thoughts, because then you can get more useful feedback and guidance, and it's easier for you to show progress as it's being made.

You can take inspiration here which is how the s/mime functionality was initially prototyped https://github.com/FlowCrypt/flowcrypt-browser/pull/2692/files

Like this, we can keep discussing for a long time but if we don't start moving forward on the goal, it wouldn't be time well spent.

So far I learned - from what you said - that forge does not produce functioning attachments. But how am I to verify this or provide help if I have no code to run? Had you at least opened a Draft PR with your changes, we'd have much better chance to have an informed discussion about it.
