### ISSUE TITLE
key.emails is undefined in compose-my-pubkey-module.ts:36

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3241]
In Firefox, when I choose my own email (`sweetalert2@gmail.com`) in the recipients input field, I'm getting this error:

![image](https://user-images.githubusercontent.com/6059356/101770798-aaae2180-3af1-11eb-9f40-821cf2efbb47.png)

```
[key.emails is undefined]
ComposeMyPubkeyModule/this.chooseMyPublicKeyBySenderEmail@moz-extension://918ae16f-cb2b-4958-849c-36d1faa30b0b/chrome/elements/compose-modules/compose-my-pubkey-module.js:29:21
ComposeStorageModule/this.getKey@moz-extension://918ae16f-cb2b-4958-849c-36d1faa30b0b/chrome/elements/compose-modules/compose-storage-module.js:30:57
async*ComposeDraftModule/this.draftSave@moz-extension://918ae16f-cb2b-4958-849c-36d1faa30b0b/chrome/elements/compose-modules/compose-draft-module.js:103:69
ComposeDraftModule/this.setHandlers/<@moz-extension://918ae16f-cb2b-4958-849c-36d1faa30b0b/chrome/elements/compose-modules/compose-draft-module.js:32:80
ComposeRecipientsModule/this.evaluateRecipients@moz-extension://918ae16f-cb2b-4958-849c-36d1faa30b0b/chrome/elements/compose-modules/compose-recipients-module.js:180:29
async*ComposeRecipientsModule/this.parseRenderRecipients@moz-extension://918ae16f-cb2b-4958-849c-36d1faa30b0b/chrome/elements/compose-modules/compose-recipients-module.js:115:32
...
```

I guess it's related to https://github.com/FlowCrypt/flowcrypt-browser/pull/3213/files#diff-fb70772926ecbff16eafe4d9ea7ca8b35cd4124bfb2b941a843f9322419b94caR36

**Comment by tomholub** [comment]
Definitely related. Can you make sure that the extension had a chance to migrate - eg by either restarting the browser, or finding a way to manually reload the extension without losing data?

That will simulate what happens when extension gets updated (which is - extension will restart, giving it a chance to do migration)

**Comment by limonte** [comment]
The same is happening in Chrome when I use another email `limon.monte@gmail.com` in the recepients field:

![b6NH3MLRFP](https://user-images.githubusercontent.com/6059356/101771905-5015c500-3af3-11eb-8af5-7077d0fcaa76.gif)

**Comment by tomholub** [comment]
Try the refresh button:

![image](https://user-images.githubusercontent.com/6306961/101771988-acbcb400-3ae2-11eb-91b1-ac976bc56083.png)

You can even go to investigate background page, see what it says in background console.

**Comment by limonte** [comment]
> Try the refresh button:
> 
> ![image](https://user-images.githubusercontent.com/6306961/101771988-acbcb400-3ae2-11eb-91b1-ac976bc56083.png)
> 
> You can even go to investigate background page, see what it says in background console.

Yup, the refresh button helped in Chrome.

**Comment by limonte** [comment]
Also, helped for Firefox. Closing, thanks @tomholub!

**Comment by tomholub** [comment]
Good to hear. When opening the extension manually, the browser doesn't know to reload it when up update the code, so the migrations won't run. Manually clicking this tells it to go through the motions as if an extension has updated.

Glad you had a chance to test it, because migrations can cause nasty bugs when they don't work properly.
