### ISSUE TITLE
Add FlowCrypt to the GitHub Student Developer Pack

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3274]
This idea was proposed by a FlowCrypt user:

> Have you thought about adding your app to the github student discount page? Lot of exposure and might get some donations. Best of luck. Thanks for the great app.

I believe they are referring to the [GitHub Student Developer Pack](https://education.github.com/pack). We have to apply to enroll in this. For more information: https://education.github.com/pack/partners

And the actual form: https://forms.gle/Wzn2c6wyiFN9orda7

**Comment by seisvelas** [comment]
Also, let me know if there is a better medium for this kind of discussion than this repo (ie, for organizational stuff not specifically related to the browser extension).

**Comment by tomholub** [comment]
This is a good place to ask this kind of question. I don't currently want to work on discounting mechanisms, but instead we could consider simply relaxing the restrictions on .edu domains so that they don't have to subscribe at all but still can use most features. It's something I'd like to do in mid-to-long term. For this issue, I'll go ahead and close :+1:
