### ISSUE TITLE
auth window not tall enough

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3373]
It wants me to scroll down to see the button lately:

![image](https://user-images.githubusercontent.com/6306961/106627696-f66ccc80-6570-11eb-81ab-9d546fab4398.png)

**Comment by limonte** [comment]
The popup looks good at my side, but there's no "See and download your contacts" in my popup. @tomholub What should I do in order to trigger the same popup as at your screenshot, with the prompt for the contacts permission?

![image](https://user-images.githubusercontent.com/6059356/107046439-4ba61980-67cf-11eb-881a-337e8ee85c21.png)

**Comment by tomholub** [comment]
I may have been using the enterprise version of the addon which asks for that. Try that - it's in the build folder next to the consumer one.

I'm also thinking, making the form a bit wider could allow for some of the text to flow horizontally, taking up less vertical space.

**Comment by limonte** [comment]
Dummy question, sorry. I should've known the answer.

![image](https://user-images.githubusercontent.com/6059356/107047496-8e1c2600-67d0-11eb-8f24-246867dbc6b9.png)

**Comment by tomholub** [comment]
Plus also that one :) but enterprise addon asks for it upfront during setup too.
