### ISSUE TITLE
reconsider s/mime usage of `serialNumber` as `fingerprint`.

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3570]
I'm afraid we can't use `serialNumber` as `fingerprint`.
Should we open a new task for this as well as include migration to re-calculate ids?

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/pull/3568#r615373569_

**Comment by tomholub** [comment]
> I'm afraid we can't use serialNumber as fingerprint.

Why is that - and what would you use instead?

**Comment by tomholub** [comment]
> We can merge this, but the original issue is still unresolved due to serialNumber vulnerability

**Comment by rrrooommmaaa** [comment]
> Why is that - and what would you use instead?

The serial number is assigned by a CA (sequentially, for example) , so we can expect it to be unique only if all certificates are coming from the same CA.
In reality we would want to accept certificates from a number of CAs, so uniqueness is not guaranteed, especially because they can be numbered '1', '2' etc. The serial number of the certificate involved in issue #3559 is actually quite short, 6 characters.
We could use the actual fingerprint of the RSA public key of the certificate, I suppose.

**Comment by rrrooommmaaa** [comment]
We also need to think about the situation when the same public key gets to our system in both  OpenPGP and S/MIME formats

**Comment by tomholub** [comment]
Thank you for noticing this. Fingerprint of the RSA key sounds good. I'd maybe prepend it with `x509-` to make sure it doesn't conflict with the same RSA key enveloped in OpenPGP.
