### ISSUE TITLE
Master is failing tests

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3610]
Tests fail, but they do not seem related to this , so to confirm I reran the tests of the latest to commit to master (which at the time ran successfully), and they now fail the same way. So tests are broken. I'll create a separate issue for that.

_Originally posted by @seisvelas in https://github.com/FlowCrypt/flowcrypt-browser/issues/3609#issuecomment-832426464_

**Comment by tomholub** [comment]
Yes, I have to take a look

**Comment by tomholub** [comment]
The issue is Auth0 changed login screen, so our selectors no longer match to automate login during tests.

It seems they are running an a/b test - sometimes it uses old format, sometimes new.

Another problem was #3601 which would always fail, also broken recently.

I'll look into Auth0 issue further.

**Comment by tomholub** [comment]
It's fixed now, although I didn't adjust anything in Auth0 handling. We'll see if it resurfaces. I did however fix various other things that were causing to often fail tests.

**Comment by tomholub** [comment]
@rrrooommmaaa tests are now fixed, sorry for delay
