### ISSUE TITLE
importing revoked keys automatically

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3637]
Agree. We should also show a clear UI to say "This key is revoked, meaning it should not be used. Importing this key will ensure that other versions of this key won't be used either." Let's do a separate PR for that.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/3579#issuecomment-841695457_

**Comment by rrrooommmaaa** [comment]
My point is: we should add a revocation entry to `revocations` store at the moment of the key analysis without user's confirmation, so that the user isn't able to import an unrevoked version of the same key later.
We can only store the fingerprint and omit the actual armored key in the `revocations` record if it potentially violates user's privacy or something.

**Comment by tomholub** [comment]
Your solution is better. Can import a whole armored key if we have a mechanism for it.
