### ISSUE TITLE
running flowcrypt first time - cannot choose another email address

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#398]

**Comment by limonte** [comment]
@tomholub please provide more details on what should be done here

**Comment by tomholub** [comment]
Before I begin setting up, I can switch accounts:

![image](https://user-images.githubusercontent.com/6306961/66210989-98915180-e6aa-11e9-8467-cca311fde62d.png)

But if I proceeded with continue with gmail:

![image](https://user-images.githubusercontent.com/6306961/66211040-b65eb680-e6aa-11e9-8198-f620e71d02b8.png)

Then clicking the account in top right does not allow me to switch accounts / set up another one.

That means if I clicked wrong and now I'm setting up another account, and want to change the account to set up, I'm stuck.

Here, you don't have to worry about current state - just make it behave like on the previous screen, pulling down a list of accounts, then redirecting to appropriate url based on which account I'm switching to.

**Comment by limonte** [comment]
Roger, thanks!

While working on this, I got a question. While working on `htm` files, it should be possible to quickly copy them to the build folders without rebuilding the whole plugin. Right now, the development process is slow for me because in order to see changes in `htm` files, I'm rebuilding the whole plugin which takes time and also kinda distracts focus.

@tomholub is there any way to copy static files (`htm`, `css`, etc.) without rebuilding the whole plugin?

**Comment by tomholub** [comment]
Not yet, but should be quite trivial to do. I'll take a look.
