### ISSUE TITLE
"end pass phrase session" conflicts with google chat?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4078]
please check if it could be adjusted, maybe with z-index

**Comment by limonte** [comment]
@tomholub do I understand correctly the issue is that the button is getting overlapped by the chat popup?

<img width="380" alt="CleanShot 2021-11-05 at 02 34 42@2x" src="https://user-images.githubusercontent.com/6059356/140439037-ecebd8e5-a725-41ce-8ae4-38ed12db0964.png">

If so, the changing `z-index` wouldn't be a proper solution because then the input filed of the chat popup would be unusable:

<img width="392" alt="CleanShot 2021-11-05 at 02 33 45@2x" src="https://user-images.githubusercontent.com/6059356/140438943-0a5f380b-8016-46a2-89a5-5be399dd38c7.png">

**Comment by tomholub** [comment]
I seems that the existing implementation is better. The user could close the chat to end pass phrase session - I think that's better than the other way around.

**Comment by limonte** [comment]
> I seems that the existing implementation is better. The user could close the chat to end pass phrase session - I think that's better than the other way around.

Agree. What we can do is to add a simple handler that would change `z-index` and bring the button on top of chat popups when the button is hovered.

**Comment by tomholub** [comment]
I didn't think about that. I thin that's a good compromise.

Let me re-shuffle the milestones a bit

**Comment by tomholub** [comment]
Please start with https://github.com/FlowCrypt/flowcrypt-browser/milestone/445

Then you can continue with https://github.com/FlowCrypt/flowcrypt-browser/milestone/446 which includes this issue

thanks!

**Comment by limonte** [comment]
> Please start with https://github.com/FlowCrypt/flowcrypt-browser/milestone/445
> 
> Then you can continue with https://github.com/FlowCrypt/flowcrypt-browser/milestone/446 which includes this issue
> 
> thanks!

Roger 👍
