### ISSUE TITLE
[question] why public key ascii armor differs from the original public key

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4281]
Description:
We received a concern about why does the ASCII armor public key differ from their original (local) public key after importing their private key on the browser extension.

For example, demo @domain.com has the following public key:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGIE5S0BEAD6AEPg8z86Z41nfLcyQaTwKMMWA1+VsgPfhZAa6g2c11qpYiO3
RUnsT5aZxTubIDXoxRUmgyBRPiH0Gdwla8GSZ+ycynFMW9DiZ/OWbW8zgNVxni0z
...
```
but when the key was imported it becomes:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: FlowCrypt Email Encryption 8.2.4
Comment: Seamlessly send and receive encrypted email

xsFNBGIE5S0BEAD6AEPg8z86Z41nfLcyQaTwKMMWA1+VsgPfhZAa6g2c11qp
....
```

I found a potential answer [here](https://stackoverflow.com/questions/23679225/how-come-the-same-gpg-key-can-have-two-different-ascii-armor), it says when a key is generated with other PGP software for example the `gpg`, the other app (OpenPGP.js) where it will be used should reformat the key - that is why it the public key visually has a two different format but has the same data/packets.

@rrrooommmaaa is it correct or was the change in public's format has a different reason?

Thank you, sir!

Reference: https://mail.google.com/mail/u/1/#inbox/FMfcgzGmtrLKjVlVQwMjBXgMJlXfzlbX

**Comment by rrrooommmaaa** [comment]
Hi @martgil 
Sure, there is some parsing/armoring happens and packets can be written in various formats, so this is possible.

**Comment by martgil** [comment]
Hello sir, @rrrooommmaaa - Thanks for your reply!

The user has a follow-up question. I have no idea how it's done (technically) at this time.

> Can you get me some more technical details?
> After I upload my private key, how is a new public key created? Is this done via a SubKey?
> I checked the source code but could not identify the correct spot(s) where this happens.

Do have some ideas about it? 

Thanks again,

**Comment by martgil** [comment]
The inquirer already found an answer - closing as per request. Thank you!

**Comment by martgil** [comment]
reopening - I have received a similar inquiry above that needs an answer from an expert PGP user.

> 1. I only wonder why FlowCrypt created a reformatted key versus using the original public key?  

sir @rrrooommmaaa, good day to you! Do you have an idea behind parsing/armoring of the imported keys that change the key's appearance? 

Is it solely because of the compatibility (keys created from other software eg. gpg should be reformated to a "format" that openpgp.js can process) or other reasons? 

Any feedback would be much appreciated!

**Comment by rrrooommmaaa** [comment]
Hi @martgil 
An OpenPGP key is parsed with `OpenPGPKey.parseMany` method which uses ` opgp.key.readArmored(text);`
https://github.com/FlowCrypt/flowcrypt-browser/blob/aab25f179a87581122cccd136ff60ac411cf1c5f/extension/js/common/core/crypto/pgp/openpgp-key.ts#L33

Later, when creating our `Key` object, the armored version is stored for future use (namely, extraction with `KeyUtil.armor`)
here 
```
(key as any).rawArmored = opgpKey.armor();
```
https://github.com/FlowCrypt/flowcrypt-browser/blob/aab25f179a87581122cccd136ff60ac411cf1c5f/extension/js/common/core/crypto/pgp/openpgp-key.ts#L249

As you see, the key is actually re-armored, so we're dependent on OpenPGP.js implementation.
I'll run a test on a couple of demo pubkeys we have in the project to see if they get changed,
or can you possibly provide a sample of such a key?

**Comment by rrrooommmaaa** [comment]
Actually, I managed to reproduce the issue with `testConstants.protonCompatPub` pubkey. I'll look into what really gets changed when re-armoring.

**Comment by rrrooommmaaa** [comment]
As for the case with `testConstants.protonCompatPub` pubkey, the re-armored key is indeed longer than the original because of an extra unhashed subpacket "issuerKeyId" was added to each signature packet, so the resulting key is 10 + 10 = 20 octets longer in binary form (and slightly more longer in armored form).
This is the piece of code that does this in OpenPGP v4
https://github.com/openpgpjs/openpgpjs/blob/1f237e6a9cbaa99fbc51ab0cfea2c55f7bd172fe/src/packet/signature.js#L312

Do I have to investigate further or try some other keys?

**Comment by martgil** [comment]
@rrrooommmaaa Thank you, sir, for your very informative reply. Code references are also so much helpful.

> Do I have to investigate further or try some other keys?

I think this will be sufficient for now. Thank you so much!

**Comment by tomholub** [comment]
@martgil you could document somewhere that some minor changes in public key formatting is expected when they are being processed. The content of the keys stays the same, but they way they are represented may look different, and that is normal and expected.

In particular, the most obvious difference is that FlowCrypt software always strips all 3rd-party signatures (when another user signs your key and redistributes it) because 3rd-party signatures can be abused.

Above that, there may be differences between how the original OpenPGP software encoded the key and how OpenPGP.js encodes the key, and again these differences are expected.

**Comment by martgil** [comment]
@tomholub may I know where would be the ideal place to put the documentation for this? thanks.

**Comment by tomholub** [comment]
on the bottom of https://flowcrypt.com/docs/technical/openpgp-compatibility.html . Also, please help me fix the css of the tables - the columns used to be more compact, so they would fit on the page.
