### ISSUE TITLE
users are unable to send encrypted-only messages

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4678]
Description:
We received a report via email and the user mentioned that they are unable to send encrypted-only messages as unticking the option "sign message" is not working.

![image](https://user-images.githubusercontent.com/46025304/189572013-983e5551-5585-42c3-aefe-3260a900f5d6.png)

Steps to reproduce:
1. open the secure compose window.
2. on the bottom-left corner of the secure compose window, click the arrow up icon next to "encrypt, sign, and send" and try to untick the option to send a sign message.
3. it won't work leaving the users to have the options `encrypted + signed` or `signed` or `plain` messages only.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQSMhrBThQKmGmZSbswVjtVzr

**Comment by martgil** [comment]
Ok, got it. 

> did the user share the use case as to why they don't want the message signed?

The user only told us about the recent change but didn't mention their use case/reason why they don't want the message signed. I sent them a reply showing an interest in humbly knowing their use case or particular reason about said changes.

**Comment by tomholub** [comment]
got it. Thanks for raising this :+1:

**Comment by emmanuelthome** [comment]
> it is by design. encrypted messages will also be signed, and it's no longer possible to send encrypted without signing.
> 
> did the user share the the use case as to why they don't want the message signed?

I'm sorry but I am rather surprised by this restriction.

Encryption and signature fulfill two very different goals. I care about the confidentiality of the messages I send, much more rarely so about their authenticity.

Signing everything exposes me to being legally bound by just about everything I send. There's no reason I would want such a blanket binding.

I might want to send something encrypted, e.g. because it is related to some form of dissent wrt my employer / my government / whatever. In such a case, I _certainly_ don't want the content to be signed: if it is, and if for some reason the recipient changes sides, gets hacked, or is forced to reveal their key, then the non-repudiability that is entailed by the cryptographic signature is likely to be sufficient evidence to fire me / put me in jail / etc.

On the other hand, an encrypted-only message is perfectly deniable (= could have been made up by the recipient, and therefore cannot legally bind me), and my point is that this is an absolutely desirable feature, in real use cases.

I hope that you will consider these arguments and waive this surprising restriction.

By the way, looking at the feature availibility chart [here](https://flowcrypt.com/docs/technical/feature-availability.html), it's claimed to be possible to only-encrypt.

![Screenshot from 2023-05-04 11-24-48](https://user-images.githubusercontent.com/2972246/236164969-0e809e41-32f6-4631-9cfe-07e942786d5b.png)

**Comment by tomholub** [comment]
Thank you for sharing details. 

The docs are outdated, we should fix that. 

We have enterprise customers who expect messages to be signed if they are encrypted, thus the requirement. It made sense to me that way, too. 

I understand what you're saying. To support your use case though, we'd have to add another client configuration option that would apply to some domains and not to others. So you can send non signed messages, while others would have signatures required. 

Although the use case you describe is perfectly valid, i'd consider it niche, within an app that already only appeals to a niche. A niche within a niche is very few people, and the dev resources would be better focused elsewhere imo. 

As things are now, we won't be spending the resources to implement this. But if an enterprise customer ever shows an interest in this feature, we may implement it, in which case the benefits would also spill over to free users.

Cheers,
