### ISSUE TITLE
The browser extension tries to decrypt an attachment named 'message' even though it contains plain/html content

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4795]
Description:
The browser extension tries to decrypt an attachment named "message" despite it contains plain or HTML content.

It will produce the following error: 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/46025304/202092841-76a04e2c-15e9-41ff-89b5-139d414a5e94.png">

For now, the affected users would have to click the 'See original' button to view the original email and 'message' attachment nicely.
<img width="229" alt="image" src="https://user-images.githubusercontent.com/46025304/202093315-d0d2ce7b-9a28-454e-acfa-0956ae979a89.png">

Sample email to replicate the issue (the one I crafted and use to replicate the issue):
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGqRZhStqHVPKPCWQGqJbbNTxfg

Sample email shared by the customers:
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGqRZhSlXHNCTqcnfjhKcTssVCV
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGqRZhSlXHNCTGSpHJRSBclGDGW

**Comment by ioanmo226** [comment]
@rrrooommmaaa, @tomholub I'm thinking about getting `attachment` data from gmail api(from attachment id) and then check if that data starts with `-----BEGIN PGP...` and ends with `-----END PGP...`.
If so, we replace with pgp block and if not, leave regular message block.

DO you have better suggestions?

**Comment by tomholub** [comment]
check just the mime type in the attachment headers? should be enough

**Comment by ioanmo226** [comment]
I don't think that's enough.
Both falsely positive email and real encrypted message mime type is `application/octet-stream`

```
// This one is output for falsely possitive encrypted email (with `message` attachment)
Get treat as
attachment.js:28 bytes: undefined
attachment.js:29 name: message
attachment.js:30 type: application/octet-stream

// Below one is output for password protected email
Get treat as
attachment.js:28 bytes: undefined
attachment.js:29 name: encrypted.asc
attachment.js:30 type: application/octet-stream
```

**Comment by tomholub** [comment]
Yes but the password-protected email name was `encrypted.asc` which is clearly encrypted message

how about any encrypted message attached as `message` attachment? maybe these have more precise mime type.

**Comment by ioanmo226** [comment]
Sorry but not sure what you are talking about.
Our current goal is to detect if email is plian/html content when message contains attachment file named `message`.
We only know attachment name, type, length, msgId, url and don't know anything if that attachment is plain/html. (i think we need to get attachment data with gmail api and check if it contains pgp block)
Currently, we treat mail as `encryptedMsg` when file name is `message`

https://github.com/FlowCrypt/flowcrypt-browser/blob/69e53e744a9e0baf129f4fdb1f99e0ae9ce63d31/extension/js/common/core/attachment.ts#L120

https://github.com/FlowCrypt/flowcrypt-browser/blob/69e53e744a9e0baf129f4fdb1f99e0ae9ce63d31/extension/js/common/core/attachment.ts#L21

**Comment by tomholub** [comment]
What I mean is, to treat any `message` attachment as encrypted is rather crude. It was certainly created because some PGP software is creating such format, with an attachment called `message`. 

What I'd like you to do is to find a sample message like that, and figure out what mime type it had. Chances are, it could be actually an attachment called `message` with `application/pgp-encrypted` mime type. Or not.

You can most likely find the message among emails stored at `flowcrypt.compatibility` gmail account. You'll need to use the gmail search functionality to find it by attachment name. Then confirm which mime type it has, from there.

If we are lucky, the mime type will be specific, and then we could differentiate whether it's encrypted or plain content in the above code without having to actually download the attachment.

------------

If you absolutely have to end up downloading the attachment after this, because it will still be some generic mime type, then use the Api.downloadChunk method or similar, which only downloads a few bytes, and then use Pgp.type method to figure out what kind of content it is from that. I'm just guessing the method names, you'd need to search for them.

**Comment by ioanmo226** [comment]
Got it.
Thanks for your brief explanation.

**Comment by ioanmo226** [comment]
Hmmm... seems like we are unlucky in this situation.
I found one message which contains `message` attachment and that mime type is also `application/octet-stream`
https://mail.google.com/mail/u/0/#inbox/FMfcgxmXJzLhdZsLmqRSNhtKnzmzLXNx

![image](https://user-images.githubusercontent.com/77344191/202702674-404d4520-9b54-4829-8d9e-e22178ea1e1c.png)

**Comment by tomholub** [comment]
if that breaks something, we'll hear from some user and will be able to get a true sample. i think it's a very fringe message format

**Comment by ioanmo226** [comment]
There are some others too(which contains `message.asc` or `message` file).
Let me check more.

**Comment by ioanmo226** [comment]
There are no other emails which contains `message` attachment. (Others contain `message.asc` or something like that).
Only 1 message with attachment file named `message` exists in compatibility email.

**Comment by tomholub** [comment]
alternative idea, in case no luck with headers, would be to require message+headers OR message +empty-email-body to judge as encrypted. 

i think this reported plain sample has a bunch of text outside of the message attachment. not common for encrypted messages.

**Comment by ioanmo226** [comment]
Ok, got it
