### ISSUE TITLE
test shared-tenant-fes some more

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4919]
we'll still test it more after I finalize setup of shared-tenant-fes, before we release

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4907#issuecomment-1409044966_

**Comment by tomholub** [comment]
Fixed shared-tenant-fes. Would be good to test:
 - client configuration retrieval 
      - (consumer) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant
      - (consumer) gmail.com - gets client configuration without ever checking fes.gmail.com
      - (consumer) other-domain.com - tries fes.other-domain.com but ends up getting empty config from shared-tenant-fes
      - (enterprise) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant
      - (consumer) gmail.com - I suppose this should show an error during setup?
      - (consumer) other-domain.com - tries fes.other-domain.com, no FES running there, shows error

**Comment by tomholub** [comment]
@martgil please test these

**Comment by tomholub** [comment]
@martgil please also test https://github.com/FlowCrypt/flowcrypt-android/pull/2171 in the exact same scenarios, and produce a table below to track the differences of behavior between the two implementations, if any.

**Comment by tomholub** [comment]
@martgil please look at this in the next few days

**Comment by martgil** [comment]
@tomholub - I'll check this real quick and let you know the results.

**Comment by martgil** [comment]
client config retrieval:
| what to test | working as described | comments |
|-------------------|--------------------------------|------------------|
| (consumer) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant | true | - |
| (consumer) gmail.com - gets client configuration without ever checking fes.gmail.com | false | it doesn't check `fes.gmail.com` but does check `gmail.com` on shared-tenant-fes endpoint and returns empty client config. eg. `{"clientConfiguration":{"flags":[]}}` ![image](https://user-images.githubusercontent.com/46025304/217734023-2cddaaf6-03cb-4e72-bc03-27ac08fa1f2f.png) | 
| (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com but ends up getting empty config from shared-tenant-fes. Check through browser network tab. | false | tried to retrieve client config from `test.flowcrypt.com` instead of `fes.test.flowcrypt.com` and returns empty config from shared-tenant-fees. eg. `{"clientConfiguration":{"flags":[]}}` ![Screenshot from 2023-02-09 14-30-07](https://user-images.githubusercontent.com/46025304/217735727-ab113958-80b2-46c4-8480-06a85890852d.png) |
| (enterprise) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant | true | - |
| (enterprise) gmail.com - I suppose this should show an error during setup? | false | I assume this is supposed to be enterprise build. An empty config is returned from shared-tenant-fes. eg. `{"clientConfiguration":{"flags":[]}}` ![image](https://user-images.githubusercontent.com/46025304/217737156-9b3ab968-84c1-40cf-88fe-c838943f06a1.png)
| (enterprise) test.flowcrypt.com - tries fes.test.flowcrypt.com, no FES running there, shows error | true | I assume this is supposed to be enterprise build. ![image](https://user-images.githubusercontent.com/46025304/217737841-c8e91dfc-b388-40ad-a9e2-9db3d66787fe.png) |

**Comment by martgil** [comment]
> @martgil please also test [FlowCrypt/flowcrypt-android#2171](https://github.com/FlowCrypt/flowcrypt-android/pull/2171) in the exact same scenarios, and produce a table below to track the differences of behavior between the two implementations, if any.

thanks - will do.

**Comment by martgil** [comment]
send messages through web portal:

| what to test | working as described | comments |
|--|--|--|
| (either build) flowcrypt.com uses fes.flowcrypt.com and works. Can also reply from the web portal | yes | can send and received encrypted emails from fes web portal. ![image](https://user-images.githubusercontent.com/46025304/217741509-9cc72699-7b2f-4eef-a4c8-fc5f62ac7c91.png)
| (either build) gmail.com uses flowcrypt.com/shared-tenant-fes and works. Can also reply from the web portal | no | there's some problem retrieving web static files for message processing on web - I'll investigate the issue now and prepare a fix when possible ![image](https://user-images.githubusercontent.com/46025304/217741161-d92b35ae-6f98-42be-b969-9a37e4d8bd73.png) |

**Comment by martgil** [comment]
Ok so there's an issue when sending opening password protected messages for user in gmail.com that uses shared-tenant-fes.:

1. The static files are hosted in fes.flowcrypt.com eg. 
```html
<script src="/lib/sha1.min.js?version=69"></script>
<script src="/lib/openpgp.min.js?version=69"></script>
<script src="/lib/jquery.min.js?version=69"></script>
<script src="/lib/purify.min.js?version=69"></script>
<script src="/lib/blob.js?version=69"></script>
<script src="/lib/FileSaver.min.js?version=69"></script>
<script src="/lib/uppy.min.js?version=69"></script>
<script src="/lib/sweetalert2.all.min.js?version=69"></script>
<script src="/lib/emailjs/punycode.js?version=69"></script>
<script src="/lib/emailjs/emailjs-stringencoding.js?version=69"></script>
<script src="/lib/emailjs/emailjs-mime-codec.js?version=69"></script>
<script src="/lib/emailjs/emailjs-mime-types.js?version=69"></script>
<script src="/lib/emailjs/emailjs-addressparser.js?version=69"></script>
<script src="/lib/emailjs/emailjs-mime-builder.js?version=69"></script>
<script src="/lib/emailjs/emailjs-mime-parser.js?version=69"></script>
<script src="/lib/web-stream-tools-bundle.js?version=69"></script>
<script src="/js/pages/web-portal-message.js?version=69"></script>

</body>
</html>
```
 meanwhile CSS are in flowcrypt.com domain - https://fes.flowcrypt.com/stylesheets/foundation.css?version=69 and https://flowcrypt.com/assets/stylesheets/foundation.css?version=69. I observed that we'd like to perform pw message decryption using fes web portal (i'd say based on the HTML structure) however the path and csp could be different when the `host` is fes (a subdomain) vs flowcrypt.com.

**Comment by tomholub** [comment]
> The static files are hosted in fes.flowcrypt.com eg.

can you link where can i see this code, where does this come from?

**Comment by tomholub** [comment]
Thank you. The static assets are broken on the shared-tenant-fes no doubt. They are not trying to get them from `fes.flowcrypt.com` as you described but from `flowcrypt.com/lib/...` where it should have been `flowcrypt.com/shared-tenant-fes-lib/...` so I don't think any header problems come into place. Just the paths need to be fixed.

**Comment by tomholub** [comment]
> (consumer) gmail.com - gets client configuration without ever checking fes.gmail.com 	no 	it doesn't check `fes.gmail.com` but does check `gmail.com` on shared-tenant-fes endpoint and returns empty client config. eg. `{"clientConfiguration":{"flags":[]}}` ![image](https://user-images.githubusercontent.com/46025304/217734023-2cddaaf6-03cb-4e72-bc03-27ac08fa1f2f.png)

This behavior is correct. It got the client configuration (fro shared-tenant-fes without ever checking fes.gmail.com)

**Comment by tomholub** [comment]
> (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com but ends up getting empty config from shared-tenant-fes. Check through browser network tab.

> tried to retrieve client config from `test.flowcrypt.com` instead of `fes.test.flowcrypt.com` and returns empty config from shared-tenant-fees. eg. `{"clientConfiguration":{"flags":[]}}` ![Screenshot from 2023-02-09 14-30-07](https://user-images.githubusercontent.com/46025304/217735727-ab113958-80b2-46c4-8480-06a85890852d.png)

This behavior is correct. It tried to get FES from `fes.test.flowcrypt.com` server, but it ended up getting the empty configuration from `shared-tenant-fes`.

Don't confuse the words **from** and **for**. Of course, users on test.flowcrypt.com should be getting client configuration **for** their own domain (test.flowcrypt.com) and in this setup should be getting it **from** shared-tenant-fes. Exactly as shown in the screenshot.

**Comment by tomholub** [comment]
> (enterprise) gmail.com - I suppose this should show an error during setup?

> I assume this is supposed to be enterprise build. An empty config is returned from shared-tenant-fes. eg. `{"clientConfiguration":{"flags":[]}}` ![image](https://user-images.githubusercontent.com/46025304/217737156-9b3ab968-84c1-40cf-88fe-c838943f06a1.png)

Ok. That's acceptable. Let's change the expectation here to `(enterprise) gmail.com - allow to proceed with setup by never checking fes.gmail.com, and getting an empty client configuration from shared-tenant-fes`, at which point the current behavior will be correct.

**Comment by martgil** [comment]
> Ok. That's acceptable. Let's change the expectation here to (enterprise) gmail.com - allow to proceed with setup by never checking fes.gmail.com, and getting an empty client configuration from shared-tenant-fes, at which point the current behavior will be correct.

That is right - I have retested it and it shows the correct behavior as described.  I already update the table above in response to this. 

I'll hide some comments that are currently resolved/clarified so that we can focus on the important ones.

**Comment by martgil** [comment]
@tomholub I just retested the other cases you've mentioned and they all produce the expected behavior. All test cases are true to be working as expected. I'm moving on to test shared-tenant-fes on android app  - please let me know if there's an additional case to test for the FlowCrypt extension. thank you!

**Comment by tomholub** [comment]
I have just updated flowcrypt.com/shared-tenant-fes to 2023-03. The link you provided https://flowcrypt.com/shared-tenant-fes/message/267920f8-9956-4cdb-b760-388fa03880ee doesn't look broken anymore but it cannot find the message. Can you re-test please, and see if the whole cycle of a web portal message works, from sending, reading, replying?

**Comment by martgil** [comment]
@tomholub you are right - the message wasn't expired either. 

I believe this condition fails from this code here: https://github.com/FlowCrypt/enterprise-server/blob/125fdc680446a6126f4c614539f58466acc055de/fes-lib/src/main/ts/pages/web-portal-message.ts#L48

Because for `fes.flowcrypt.com`, the URL is `https://fes.flowcrypt.com/message/....` which gets the message id
![image](https://user-images.githubusercontent.com/46025304/219559409-dff37652-8968-4577-88d9-c8f9ecfae121.png)

Unlike for normal users, the URL for a password-protected message is `flowcrypt.com/shared-tenant-fes/message/...` - the condition check is false and returns no messageId.
![image](https://user-images.githubusercontent.com/46025304/219559191-40fa927c-48b8-4294-a078-d93a4a3c978c.png)

**Comment by martgil** [comment]
I change the condition on the fly (thru response manipulation) and indeed it was the code that needs to be changed. But not only that, the message file wasn't downloaded, but it was here https://flowcrypt.com/shared-tenant-fes/api/v1/message/23240c8f-9221-4a23-9073-f2b3181a6a2d

![image](https://user-images.githubusercontent.com/46025304/219563508-96f9d275-7f3f-4061-b4af-fd5c1f6a2a4e.png)

message on fes https://fes.flowcrypt.com/api/v1/message/0b877200-d5d6-4764-a43e-f5e6d9d5f365 is downloadable and repliable.

**Comment by martgil** [comment]
Yes, sir. I'm preparing a PR for it.

**Comment by tomholub** [comment]
@martgil I have just updated shared-tenant-fes to 2023-04. Please do another round of end-to-end testing of the password message, make sure they work, and that replies from web portal also work.

**Comment by martgil** [comment]
@tomholub shared-tenant-fes is partially not working. I think we need to make adjustment on s3 settings or something.

1.) Access to XMLHttpRequest at 'https://shared-tenant-fes-web-portal.s3.eu-central-1.amazonaws.com/message/86b1d69e-39e6-4878-9b53-036175d589e8' from origin 'https://flowcrypt.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. [possible solution: is to add `Access-Control-Allow-Origin: https://flowcrypt.com` on s3's response or similar to it.]


2.) The supposed downloadable message returns 403 https://shared-tenant-fes-web-portal.s3.eu-central-1.amazonaws.com/message/86b1d69e-39e6-4878-9b53-036175d589e8 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>W5VR5VTN03C6XAHN</RequestId>
<HostId>SIT0tHlfpJ5vGxfsG+hsEROVI2Mn2O7vMV/JPHpSZAZEQAH0poRWOIbDCZyW/FrGloa3BzrhbNU=</HostId>
</Error>
```

[possible solution: The public access might not be allowed?]

**Comment by martgil** [comment]
@tomholub shared-tenant-fes message retrieval and reply functionality are all working now. thank you!

![image](https://user-images.githubusercontent.com/46025304/221086882-5e330328-475f-4d67-b104-8515c0ab67c0.png)

![image](https://user-images.githubusercontent.com/46025304/221086971-25f352d0-c56b-46d4-862d-74b74eb8c2e1.png)
