### ISSUE TITLE
Failed parsing of signed message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5029]
Browser extension fails to parse signed message with attached signature

<img width="360" alt="Screenshot 2023-03-20 at 14 38 15" src="https://user-images.githubusercontent.com/1062093/226341267-cb233712-5bfb-40e4-9953-4a67a6931938.png">

@ioanmo226 please work on this issue after finishing your current one, I forwarded you email with attached `.eml`

**Comment by ioanmo226** [comment]
Ok, got it

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-browser/blob/6ff785cc55d3f892ffdea8609871628f8cfb2884/extension/js/common/core/mime.ts#L368

@sosnovsky For customer's email `node._childNodes[1]` content type is `text/plain`. That's why it can't parse this message.
Maybe we also need to add another condition where `node._childNodes[1].rawContent` starts `-----BEGIN PGP SIGNATURE-----` and ends with `-----END PGP SIGNATURE-----`?
Or you have other idea?

Please check and let me know.

![image](https://user-images.githubusercontent.com/77344191/226533866-55cacdeb-0be1-41e6-a0f4-688d26a8eaf5.png)

**Comment by sosnovsky** [comment]
@ioanmo226 let's check if node name is equal to `signature.asc` (like we do in iOS - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/Core/source/core/att.ts#L89)

**Comment by ioanmo226** [comment]
Sounds good
