### ISSUE TITLE
Tables are not rendered in emails

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5111]
Customer reported an issue with tables rendering - they're not showing in emails.

**Comment by sosnovsky** [comment]
@ioanmo226 please work on this one after your current issue.
I'll send you email with this error for reproducing

**Comment by ioanmo226** [comment]
Ok

**Comment by ioanmo226** [comment]
@sosnovsky, I just checked the email and found out why the table content is not showing.
The issue is that the `width` was set to 0px for the `table` and the `colgroup` node under the `table` node was removed. To resolve the issue, we can either change the `width` to `auto` or add the `colgroup` node back.

I suggest that we investigate why the colgroup node was removed and address the root cause to prevent this issue from happening again.

What do you think?

![image](https://user-images.githubusercontent.com/77344191/234088435-938bbd79-f332-4072-8ecf-e7d928896fb3.png)

**Comment by sosnovsky** [comment]
> I suggest that we investigate why the colgroup node was removed and address the root cause to prevent this issue from happening again.

For sure, let's work on fixing root cause and finding why `colgroup` was removed, as it probably can lead to other issues too.
