### ISSUE TITLE
Contacts search results sometimes not reliable

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5131]
For example, in `flowcrypt.compatibility@gmail.com` account try to enter recipient starting with `vict` - google compose returns 2 contacts, while FlowCrypt search shows `No Contacts found`

Also sometimes searching for public keys takes too long and FlowCrypt search section shows `No Contacts found` while keys are searching:
1) I have `some@test.com` as contact
2) entering `some` as recipient in google compose returns `some@test.com` as search result
3) entering `some` as recipient in FlowCrypt compose shows `No Contacts found` as result, but I checked console and there were some requests searching for public key (https://keys.openpgp.org/vks/v1/by-email/some@test.com, https://flowcrypt.com/attester/pub/some@test.com ...). After they finished search results changed to `some@test.com`, but it took 7-8 seconds, I think.

So it seems search results are rendered only when public keys search is finished, but it can be confusing to users when search takes longer than usual. For this case let's render search results instantly and show some loader instead of `lock` icon, while public keys are searched.

**Comment by ioanmo226** [comment]
> For example, in flowcrypt.compatibility@gmail.com account try to enter recipient starting with vict - google compose returns 2 contacts, while FlowCrypt search shows No Contacts found

Both the Google `people:searchContacts` and `otherContacts:search` APIs return zero results for the `vict` query, even though there are contacts with email addresses user+victim@gmail.com and user+victim2@gmail.com in the account's contact list. I think this is an issue with the Google API. It's possible that the `otherContacts` API doesn't return results for the vict query because it comes after the `+` sign.

I haven't been able to find any other Google APIs that can return results for the `vict` query besides `people:searchContacts` and `otherContacts:search`.

@sosnovsky, what is your opinion on this?

**Comment by sosnovsky** [comment]
Yeah, these endpoints search only by start string of email, as [documentation](https://developers.google.com/people/api/rest/v1/otherContacts/search#query-parameters) says:
> The query is used to match prefix phrases of the fields on a person. For example, a person with name "foo name" matches queries such as "f", "fo", "foo", "foo n", "nam", etc., but not "oo n".

Gmail compose box uses internal endpoint https://people-pa.clients6.google.com/$rpc/google.internal.people.v2.minimal.PeopleApiAutocompleteMinimalService/ListAutocompletions, which isn't available through API.

Then let's fix just showing of search results during public key lookup.
