### ISSUE TITLE
Prepare new screenshots for Chrome Web Store

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-browser#5236]
@vahram-papazyan could later prepare new screenshots that, once you two are happy with them, I'll upload to the web store. I'm unsubscribing until then, please assign me once ready. Thanks!

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/5228#issuecomment-1596926211_

**Comment by vahram-papazyan** [comment]
Screens
![1  Seamlessly Send PGP-Encrypted Messages](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/28fb065c-82cf-4c99-ba83-d3f09aa9ef67)
![2  setup for users](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/05d2c35e-a372-461e-ac56-c05a796f43e2)

**Comment by sosnovsky** [comment]
Looks like this issue is just a duplicate of https://github.com/FlowCrypt/flowcrypt-browser/issues/5228 ?

Images should have size [1280x800](https://developer.chrome.com/docs/webstore/images/#:~:text=Each%20screenshot%20should%20be%20as,1280x800%20or%20640x400%20pixels) and include text as current ones ("Seamlessly send PGP Encrypted Messages", "Setup for Basic and Advanced Users" etc)

**Comment by vahram-papazyan** [comment]
> Looks like this issue is just a duplicate of https://github.com/FlowCrypt/flowcrypt-browser/issues/5228 ?

yeah, I'll close this issue.
