### ISSUE TITLE
Message and attachments overlap 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#535]
![Uploading Screen Shot 2017-02-26 at 1.40.58 AM.png…]()

**Comment by tomholub** [comment]
Don't see the image but I think I know what you mean

**Comment by tomholub** [comment]
First of all, I think the attachments should be styled as `flow:right` or `flow:letf`. Then they should stack to the left of each other, until they form a second line from the bottom.

That way at least they all fit on the screen.

**Comment by mondo989** [comment]
I like how it never attached :o

**Comment by tomholub** [comment]
Repro: add 10 attachments to a reply with a short message body and notice it overflow

![image](https://user-images.githubusercontent.com/6306961/53565446-70a8a100-3b51-11e9-8e48-6971e08976a8.png)

Only grab this issue if you are very comfortable changing a bunch of html/css in addition to (possibly) a bit of js. 

I'm thinking the attachments should be in their own table row, which should have no height if there are no attachments. Then the attachments inside should be `inline-block` so that they go to the right of one another, until they form a second row and the containing `td` expands. That way they don't overlap with text.
