### ISSUE TITLE
Additional new line gets added on Gmail user's email signature

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5354]
Description: When rendering a Gmail user's email signature, the FlowCrypt browser extension adds an additional new line for every line ever found on the user's email signature.

Moreover, the user is only using a text/plain email signature.

Sample:

(original gmail signature)
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/96adc2c4-2e4e-4b14-947a-ecc870f11ea2)

(flowcrypt rendered gmail signature)
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/2fcfa1a5-27ca-4976-97ac-546ef1e0115e)

Expected behavior: The user email signature should retain if it is plain/text only for the user to have the desired format.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwWJwMTRbKBJJhcddPbZvWsNz

**Comment by martgil** [comment]
I was unable to reproduce the issue on version 8.5.0; however, using the method of copying and pasting with (CTRL+SHIFT+V) gave the user the expected correct result. One thing to note is that the encrypted message where the problem exists is composed of the FlowCrypt browser extension version 8.4.8.

**Comment by sosnovsky** [comment]
For me this issue is still present on 8.5.0

gmail settings
<img width="490" alt="Screenshot 2023-08-23 at 11 29 15" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/e9cd65f6-1cfb-4775-94c5-b6cb5eac09e7">

FlowCrypt extension local storage
<img width="194" alt="Screenshot 2023-08-23 at 11 28 54" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/57fe4947-7c7b-42c4-99f0-9dbe85691d01">

FlowCrypt compose box
<img width="270" alt="Screenshot 2023-08-23 at 11 28 37" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/20672d60-221e-401c-9d82-6baa85df41e7">

**Comment by martgil** [comment]
Thanks @sosnovsky I will re-check this issue again. Btw, did you just type the Gmail signature?

**Comment by sosnovsky** [comment]
> Btw, did you just type the Gmail signature?

No, it's configured this way for several months, I think

**Comment by sosnovsky** [comment]
Hmm, I tried to create a new signature and it works well:

<img width="297" alt="Screenshot 2023-08-23 at 11 49 47" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/83712d60-2893-4d3f-a468-e997cba08d1b">

I'll reassign this task to myself, as I can reproduce it with my old signature
