### ISSUE TITLE
Fix "Unchecked runtime.lastError" in console logs

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5433]
There are a lot of `Unchecked runtime.lastError` errors with different messages in console:
```
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
Unchecked runtime.lastError: The message port closed before a response was received.
```
<img width="900" alt="Screenshot 2023-09-29 at 16 24 59" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/4461c031-05e0-45a1-8b20-30d60ccbfdb4">
<img width="900" alt="Screenshot 2023-09-29 at 16 25 07" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/705fa1d1-ff6a-4187-98d7-4ac8a849ba6e">

**Comment by ioanmo226** [comment]
Currently having a deep look at this issue.
But haven't found exact cause yet.
Digging more now

**Comment by sosnovsky** [comment]
As I understand, it happens when some message sent with `sendMessage` expects callback, but doesn't receive it.
We can try to temporarily disable some messages and check if error still occurs, to find which message causes this error.
Then it'll be easier to find exact place where errors happen

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-browser/pull/5651#issuecomment-2047444888
This error indeed occurred after implementing fetch, but upon researching, it seems not to stem from the fetch implementation itself.
Rather, it appears to be related to changes in Chrome's behavior.

Even when testing with earlier versions from 2023, the error persists.
The exact cause is still unclear, but it might be due to some of our code logic not being compatible with the latest Chrome standards.

**Comment by sosnovsky** [comment]
Do you think it will be possible to find which part of code causes this issue, to make it compatible with Chrome changes?

**Comment by ioanmo226** [comment]
Still haven't found yet.
Trying to dig deeper.
