### ISSUE TITLE
cryptup_reply as MIME header

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#5528]
ref #5004 

As it's our custom realization maybe we can move cryptup_reply to the MIME header

Instead of 

```Content-Type: multipart/mixed;
 boundary="----sinikael-?=_1-17026243038870.873205968994909"
Date: Fri, 15 Dec 2023 07:11:43 +0000
Message-Id: <1702624303893-03e290a0-c2e5389a-e96f7650@localhost>
MIME-Version: 1.0

------sinikael-?=_1-17026243038870.873205968994909
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

Some encrypted reply

On 12/14/2023, 4:49:05 PM, den@flowcrypt.com wrote:

Encrypted text



<div style=3D"display: none;" class=3D"cryptup_reply" =
cryptup-data=3D"some_data"></div>
------sinikael-?=_1-17026243038870.873205968994909--
```

we can have

```Content-Type: multipart/mixed;
 boundary="----sinikael-?=_1-17026243038870.873205968994909"
Date: Fri, 15 Dec 2023 07:11:43 +0000
Message-Id: <1702624303893-03e290a0-c2e5389a-e96f7650@localhost>
MIME-Version: 1.0
Cryptup-reply: some_data //LOOK AT THIS PLACE

------sinikael-?=_1-17026243038870.873205968994909
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

Some encrypted reply

On 12/14/2023, 4:49:05 PM, den@flowcrypt.com wrote:

Encrypted text
```

In that case, we don't need to think about rendering at all.

@sosnovsky what do you think?

**Comment by sosnovsky** [comment]
Original issue happens because FES reply has body `text/plain`, but it includes `<div>` which is then rendered as plain text.

Simpler solution will be to change FES reply body type to `text/html`, and then this `<div>` won't be rendered as it has `display: none` property. We have this change planned, probably for the next enterprise-server release (https://github.com/FlowCrypt/enterprise-server/issues/4938), as it needs users to have at least 8.5.0 browser extension release.
