### ISSUE TITLE
Attachments are not decrypted in Gmail offline mode

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5766]
When using [Gmail offline mode](https://support.google.com/mail/answer/1306849?hl=en) it's possible to decrypt encrypted messages, but encrypted attachments are downloaded encrypted. Gmail automatically downloads email attachments when offline mode is enabled, while FlowCrypt uses API calls for fetching attachments data.
Need to check if it's possible to access offline attachments stored by Gmail and then use their data for decryption.

**Comment by sosnovsky** [comment]
@ioanmo226 please check this issue before continuing ESLint migration, thanks!
It was a customer request, who're interested in such ability for offline mode.

**Comment by ioanmo226** [comment]
Okay

**Comment by ioanmo226** [comment]
Hi,
I've looked into it thoroughly, and it seems that due to security reasons, it's not possible to access offline saved attachment data.
Below is Bard's answer (we can't trust it 100%, but based on my findings, it seems accurate).
I think we should brainstorm about this if we must implement this functionality. Maybe let user download attachment first and drag & drop into decrypt window? Not sure yet though

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/d5b3d285-6165-4231-b3b4-3fb5456cfb4d)

**Comment by sosnovsky** [comment]
Thanks for checking! Seems like adding separate tool for decrypting downloaded attachments will be the most reliable solution. I'll check with customer if it'll work for them. Will keep you updated!

**Comment by ioanmo226** [comment]
Okay

**Comment by sosnovsky** [comment]
This solution was accepted by customer ✅
