### ISSUE TITLE
Message loading is stuck in Firefox

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5770]
When trying to open encrypted message in Firefox - it just stucks on `Loading...` label and browser hangs out.

**Comment by ioanmo226** [comment]
You mean in gmail page or in extension page?

**Comment by ioanmo226** [comment]
Couldn't reproduce issue in gmail page but can reproduce in extension page

**Comment by ioanmo226** [comment]
Anyway, There's indeed an issue for firefox

**Comment by sosnovsky** [comment]
The same issue happens in Chrome when you directly open encrypted thread in `encrypted inbox`:
- open `encrypted inbox`
- open encrypted thread - messages successfully decrypted
- reload thread page - messages stuck in `loading...` state

@ioanmo226 let's work on this issue next, so we'll be able to publish new Firefox release, as this bug makes it impossible to use extension in Firefox

**Comment by ioanmo226** [comment]
@sosnovsky,

I've taken a detailed look at this issue and I think it warrants a brainstorming session. Currently, both the `GmailElementReplacer` (content script) and `InboxView` use `messageRenderer` to download and process messages.
https://github.com/FlowCrypt/flowcrypt-browser/blob/854059046cfd1b3c0fa66d5b3d5c7c5dcdd5f406/extension/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.ts#L170

Once the PGP block is ready, we attempt to render it. However, the problem is that the PGP block remains stuck in a `loading` state when loaded by itself because there's no message rendering mechanism within the PGP block frame. It heavily relies on `GmailElementReplacer` when loaded on a Gmail page with a content script, and on `InboxView` when the user accesses the extension inbox page and opens individual PGP block views.

https://github.com/FlowCrypt/flowcrypt-browser/blob/9fa013af570f6d74846b622fc0a344cece3d1d2f/extension/chrome/elements/pgp_block.ts#L69

So, I think we should implement a message rendering logic in the PGP block frame as well. The downside is that the message rendering logic will be duplicated (in both the PGP block frame and `GmailElementReplacer`/`InboxView`).

What are your thoughts on this?

**Comment by sosnovsky** [comment]
But it works well in Chrome - I haven't noticed similar issue there. My assumption was that `BrowserMsg.send` fails in some cases on Firefox, so `pgpBlockReady` event isn't received by pgp block and causes its stuck in `loading...` state.
I'll send you video of this issue by email.

> So, I think we should implement a message rendering logic in the PGP block frame as well. The downside is that the message rendering logic will be duplicated (in both the PGP block frame and GmailElementReplacer/InboxView).

As I remember, previously we've had such duplicated logic, and last year moved it to `MessageRenderer`, it'll be better to keep it there in a single place.

**Comment by ioanmo226** [comment]
But in chrome, message decryption (in extension inbox page `../inbox.htm?threadId=${threadId}..`)doesn't work well when there are multiple messages in thread. (one of message decryption doesn't work and it is stuck at loading)

let me have a deep look.

**Comment by sosnovsky** [comment]
It's strange, but mentioned issue doesn't occur for me anymore - I opened encrypted thread, waited 30-40 seconds until `loading...` label disappeared and error message appeared - `Cannot get reply data for the message you are replying to.`, which means that [fetchReplyMeta](https://github.com/FlowCrypt/flowcrypt-browser/blob/c35c5e8bc50ef329e14d7348ff84aaa704790da5/extension/chrome/elements/compose-modules/compose-render-module.ts#L219) request failed.
I tried to add some logs for finding original error, but since then message loading doesn't stuck - works well on gmail page and in encrypted inbox.
