### ISSUE TITLE
allow rendering HTML messages

### ISSUE THREAD

**Issue by shayani** [FlowCrypt/flowcrypt-browser#706]
When I receive a multi-part messagem (ex: from Facebook, with encryption), CryptUp decrypts it correctly, but shows only the TEXT part of the message. The HTML part I can see using other tools (ex: GPGSuite for Apple Mail)

**Comment by tomholub** [comment]
This is currently on purpose / by design. There's certain liability in rendering untrusted HTML because you need to make 100% sure that no malicious parts slipped through.

If there is plain text, it will render the plain text (after sanitizing it). If there's html, it will convert it to plain text and then sanitize + display it.

This is the safest way to do it for now. If I wanted to display HTML (coming from untrusted sources), that solution would absolutely require an external 3rd party security review to make sure it's done properly. I don't have resources for that at the moment.

**Comment by shayani** [comment]
I understand. Thanks!

**Comment by tomholub** [comment]
I'll happily keep this open though - one day :)

**Comment by tomholub** [comment]
#1265  prioritize html
