### ISSUE TITLE
empty message shows an unnecessary scrollbar

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#959]
To reproduce:
1) secure compose
2) leave text empty
3) send
4) confirm empty
5) open sent message

**Comment by tomholub** [comment]
just change minimum allowed height somewhere in resizeReplyBox

**Comment by vincentp** [comment]
Checked that one, but it looked fine to me (on Chrome), which browser did you use?
https://www.dropbox.com/s/c64mnsyst9zkqua/Screenshot%202019-02-15%2013.49.02.png?dl=0

When I hit reply, there is a scrollbar on the body (depends on your screen size) because of a 200px bottom padding. Maybe that's what you are talking about?
https://www.dropbox.com/s/kgjqgorsbotu0z5/Screenshot%202019-02-15%2014.00.27.png?dl=0

It would be good to include screenshots + browser info when it's related to the UI.

**Comment by tomholub** [comment]
Send an encrypted message to someone that has encryption set up, where you don't need to use a one time password. Then when you open the message, you should see the scrollbar.

Encountered on mail.google.com

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/52863992-1a8b3500-3131-11e9-9c29-4b6b6da0940a.png)

This was on FF but I'm pretty sure it does that on Chrome too

**Comment by schmorrison** [comment]
The problem seems to occur due to the following CSS in `.pgp_secure` class:

```
  padding-top: 6px;
  padding-bottom: 6px;
```

It occurs in the FC Inbox and the message in Gmail also. Removing the padding-top and padding-bottom styles fixes the scrollbar issue, but when there is any content in the message then the block seem awfully squeezed.

Here is an image with the padding styles disabled:

![image](https://user-images.githubusercontent.com/17385251/53144090-73f3c980-3560-11e9-9f07-c965e8d30750.png)

And antoher with the padding enabled:

![image](https://user-images.githubusercontent.com/17385251/53144179-de0c6e80-3560-11e9-8495-4c46d81f3d8f.png)

A possible fix, could be while rendering each decrypted block, if the block has no content then set the CSS of that specific element as ```padding-top: 0px;padding-bottom: 0px;```.

While trying to figure out this problem, I came across another issue that I created: #1566

**Comment by tomholub** [comment]
Since this only happens to the messages with smallest height, the solution was to give it a minimum height when resizing. I went ahead and fixed it.
